// Code generated by go generate; DO NOT EDIT.

package agentregistry

var registeredNPXAgents = []registryNPXAgent{
	{
		Agent: ConnectableAgent{
			ID: "agoragentic-acp", DisplayName: "Agoragentic", Version: "1.3.0", RegistryID: "agoragentic-acp",
			Description: "Agent marketplace with 174+ AI capabilities. Browse, invoke, and pay for agent services settled in USDC on Base L2.",
		},
		Package: "agoragentic-mcp@1.3.0",
		Args:    []string{"--acp"},
	},
	{
		Agent: ConnectableAgent{
			ID: "auggie", DisplayName: "Auggie CLI", Version: "0.33.0", RegistryID: "auggie",
			Description: "Augment Code's powerful software agent, backed by industry-leading context engine",
		},
		Package: "@augmentcode/auggie@0.33.0",
		Args:    []string{"--acp"},
		Env: map[string]string{
			"AUGMENT_DISABLE_AUTO_UPDATE": "1",
		},
	},
	{
		Agent: ConnectableAgent{
			ID: "autohand", DisplayName: "Autohand Code", Version: "0.2.1", RegistryID: "autohand",
			Description: "Autohand Code - AI coding agent powered by Autohand AI",
		},
		Package: "@autohandai/autohand-acp@0.2.1",
	},
	{
		Agent: ConnectableAgent{
			ID: "claude", DisplayName: "Claude Agent", Version: "0.63.0", RegistryID: "claude-acp",
			Description: "ACP wrapper for Anthropic's Claude",
		},
		Package: "@agentclientprotocol/claude-agent-acp@0.63.0",
	},
	{
		Agent: ConnectableAgent{
			ID: "cline", DisplayName: "Cline", Version: "3.0.46", RegistryID: "cline",
			Description: "Autonomous coding agent CLI - capable of creating/editing files, running commands, using the browser, and more",
		},
		Package: "cline@3.0.46",
		Args:    []string{"--acp"},
	},
	{
		Agent: ConnectableAgent{
			ID: "codebuddy-code", DisplayName: "Codebuddy Code", Version: "2.106.7", RegistryID: "codebuddy-code",
			Description: "Tencent Cloud's official intelligent coding tool",
		},
		Package: "@tencent-ai/codebuddy-code@2.106.7",
		Args:    []string{"--acp"},
	},
	{
		Agent: ConnectableAgent{
			ID: "codex", DisplayName: "Codex", Version: "1.1.7", RegistryID: "codex-acp",
			Description: "ACP adapter for OpenAI's coding assistant",
		},
		Package: "@agentclientprotocol/codex-acp@1.1.7",
	},
	{
		Agent: ConnectableAgent{
			ID: "deepagents", DisplayName: "DeepAgents", Version: "0.1.7", RegistryID: "deepagents",
			Description: "Batteries-included AI coding and general purpose agent powered by LangChain.",
		},
		Package: "deepagents-acp@0.1.7",
	},
	{
		Agent: ConnectableAgent{
			ID: "dimcode", DisplayName: "DimCode", Version: "0.2.37", RegistryID: "dimcode",
			Description: "A coding agent that puts leading models at your command.",
		},
		Package: "dimcode@0.2.37",
		Args:    []string{"acp"},
	},
	{
		Agent: ConnectableAgent{
			ID: "dirac", DisplayName: "Dirac", Version: "0.4.28", RegistryID: "dirac",
			Description: "Reduces API costs by more than 50%, produces better and faster work. Uses Hash anchored parallel edits, AST manipulation and a whole lot of neat optimizations. Fully Open Source.",
		},
		Package: "dirac-cli@0.4.28",
		Args:    []string{"--acp"},
	},
	{
		Agent: ConnectableAgent{
			ID: "factory-droid", DisplayName: "Factory Droid", Version: "0.181.0", RegistryID: "factory-droid",
			Description: "Factory Droid - AI coding agent powered by Factory AI",
		},
		Package: "droid@0.181.0",
		Args:    []string{"exec", "--output-format", "acp-daemon"},
		Env: map[string]string{
			"DROID_DISABLE_AUTO_UPDATE":         "true",
			"FACTORY_DROID_AUTO_UPDATE_ENABLED": "false",
		},
	},
	{
		Agent: ConnectableAgent{
			ID: "gemini", DisplayName: "Gemini CLI", Version: "0.52.0", RegistryID: "gemini",
			Description: "Google's official CLI for Gemini",
		},
		Package: "@google/gemini-cli@0.52.0",
		Args:    []string{"--acp"},
	},
	{
		Agent: ConnectableAgent{
			ID: "copilot", DisplayName: "GitHub Copilot", Version: "1.0.75", RegistryID: "github-copilot-cli",
			Description: "GitHub's AI pair programmer",
		},
		Package: "@github/copilot@1.0.75",
		Args:    []string{"--acp"},
	},
	{
		Agent: ConnectableAgent{
			ID: "glm-acp-agent", DisplayName: "GLM Agent", Version: "1.3.0", RegistryID: "glm-acp-agent",
			Description: "ACP agent powered by Zhipu AI's GLM Coding Plan models (glm-5.1, glm-5-turbo, glm-4.7, glm-4.5-air). Supports streaming, tool calls, mid-session model switching, image input via Z.AI Coding Plan Vision MCP, and session load/fork/resume with on-disk persistence.",
		},
		Package: "glm-acp-agent@1.3.0",
	},
	{
		Agent: ConnectableAgent{
			ID: "grok", DisplayName: "Grok Build", Version: "0.2.112", RegistryID: "grok-build",
			Description: "xAI's coding agent and CLI",
		},
		Package: "@xai-official/grok@0.2.112",
		Args:    []string{"agent", "stdio"},
	},
	{
		Agent: ConnectableAgent{
			ID: "kilo", DisplayName: "Kilo", Version: "7.4.16", RegistryID: "kilo",
			Description: "The open source coding agent",
		},
		Package: "@kilocode/cli@7.4.16",
		Args:    []string{"acp"},
	},
	{
		Agent: ConnectableAgent{
			ID: "nova", DisplayName: "Nova", Version: "1.1.29", RegistryID: "nova",
			Description: "Nova by Compass AI - a fully-fledged software engineer at your command",
		},
		Package: "@compass-ai/nova@1.1.29",
		Args:    []string{"acp"},
	},
	{
		Agent: ConnectableAgent{
			ID: "pi-acp", DisplayName: "pi ACP", Version: "0.0.32", RegistryID: "pi-acp",
			Description: "ACP adapter for pi coding agent",
		},
		Package: "pi-acp@0.0.32",
	},
	{
		Agent: ConnectableAgent{
			ID: "qoder", DisplayName: "Qoder CLI", Version: "0.2.14", RegistryID: "qoder",
			Description: "AI coding assistant with agentic capabilities",
		},
		Package: "@qoder-ai/qodercli@0.2.14",
		Args:    []string{"--acp"},
	},
	{
		Agent: ConnectableAgent{
			ID: "qwen-code", DisplayName: "Qwen Code", Version: "0.21.0", RegistryID: "qwen-code",
			Description: "Alibaba's Qwen coding assistant",
		},
		Package: "@qwen-code/qwen-code@0.21.0",
		Args:    []string{"--acp", "--experimental-skills"},
	},
	{
		Agent: ConnectableAgent{
			ID: "sigit", DisplayName: "siGit Code", Version: "1.5.0", RegistryID: "sigit",
			Description: "Local-first coding agent. Runs entirely on your machine with optional on-device LLM inference via Onde.",
		},
		Package: "@smbcloud/sigit@1.5.0",
	},
}
