package windows

const sandboxPythonSiteCustomize = `# Generated by Caelis Windows sandbox.
# Python 3.13+ creates tempfile.mkdtemp directories with a private Windows DACL
# for mode 0700. That private DACL is not compatible with WRITE_RESTRICTED
# tokens, so sandbox-local temp directories need normal inherited ACLs.
import errno as _errno
import os as _os
import sys as _sys
import tempfile as _tempfile

_caelis_orig_mkdtemp = _tempfile.mkdtemp
_caelis_sandbox_temp = _os.environ.get("CAELIS_SANDBOX_TEMP", "")
_caelis_audit = getattr(_sys, "audit", None)

def _caelis_norm(path):
    if path is None:
        return ""
    try:
        return _os.path.normcase(_os.path.abspath(_os.fsdecode(path)))
    except Exception:
        return ""

def _caelis_under_sandbox_temp(path):
    root = _caelis_norm(_caelis_sandbox_temp)
    value = _caelis_norm(path)
    return bool(root and (value == root or value.startswith(root + _os.sep)))

def _caelis_mkdtemp(suffix=None, prefix=None, dir=None):
    if _os.name != "nt" or not _caelis_sandbox_temp or _sys.version_info < (3, 13):
        return _caelis_orig_mkdtemp(suffix=suffix, prefix=prefix, dir=dir)
    prefix, suffix, dir, output_type = _tempfile._sanitize_params(prefix, suffix, dir)
    if not _caelis_under_sandbox_temp(dir):
        return _caelis_orig_mkdtemp(suffix=suffix, prefix=prefix, dir=dir)
    names = _tempfile._get_candidate_names()
    if output_type is bytes:
        names = map(_os.fsencode, names)
    for seq in range(_tempfile.TMP_MAX):
        name = next(names)
        file = _os.path.join(dir, prefix + name + suffix)
        try:
            if _caelis_audit is not None:
                _caelis_audit("tempfile.mkdtemp", file)
            _os.mkdir(file, 0o777)
        except FileExistsError:
            continue
        except PermissionError:
            if _os.path.isdir(dir) and _os.access(dir, _os.W_OK):
                continue
            raise
        return _os.path.abspath(file)
    raise FileExistsError(_errno.EEXIST, "No usable temporary directory name found")

if _os.name == "nt" and _caelis_sandbox_temp and _sys.version_info >= (3, 13):
    _tempfile.mkdtemp = _caelis_mkdtemp
`
