// Command acp_registry_generate refreshes the checked-in npx-compatible ACP
// Registry snapshot used by local Agent onboarding.
package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"io"
	"net/http"
	"os"
	"sort"
	"strconv"
	"strings"
	"time"
)

const defaultRegistryURL = "https://cdn.agentclientprotocol.com/registry/v1/latest/registry.json"

type registryDocument struct {
	Agents []registryAgent `json:"agents"`
}

type registryAgent struct {
	ID           string               `json:"id"`
	Name         string               `json:"name"`
	Version      string               `json:"version"`
	Description  string               `json:"description"`
	Distribution registryDistribution `json:"distribution"`
}

type registryDistribution struct {
	NPX *registryNPX `json:"npx"`
}

type registryNPX struct {
	Package string            `json:"package"`
	Args    []string          `json:"args"`
	Env     map[string]string `json:"env"`
}

func main() {
	source := flag.String("source", defaultRegistryURL, "registry URL or local JSON file")
	output := flag.String("output", "catalog_registry_generated.go", "generated Go output")
	flag.Parse()
	if err := run(strings.TrimSpace(*source), strings.TrimSpace(*output)); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(source string, output string) error {
	if source == "" {
		return errors.New("acp registry generate: source is required")
	}
	if output == "" {
		return errors.New("acp registry generate: output is required")
	}
	raw, err := readSource(source)
	if err != nil {
		return err
	}
	var registry registryDocument
	if err := json.Unmarshal(raw, &registry); err != nil {
		return fmt.Errorf("acp registry generate: decode %q: %w", source, err)
	}
	generated, count, err := render(registry)
	if err != nil {
		return err
	}
	if count == 0 {
		return fmt.Errorf("acp registry generate: %q contained no npx Agents", source)
	}
	if err := os.WriteFile(output, generated, 0o644); err != nil {
		return fmt.Errorf("acp registry generate: write %q: %w", output, err)
	}
	return nil
}

func readSource(source string) ([]byte, error) {
	if !strings.HasPrefix(source, "https://") {
		raw, err := os.ReadFile(source)
		if err != nil {
			return nil, fmt.Errorf("acp registry generate: read %q: %w", source, err)
		}
		return raw, nil
	}
	client := &http.Client{Timeout: 30 * time.Second}
	response, err := client.Get(source)
	if err != nil {
		return nil, fmt.Errorf("acp registry generate: fetch %q: %w", source, err)
	}
	defer response.Body.Close()
	if response.StatusCode < 200 || response.StatusCode >= 300 {
		return nil, fmt.Errorf("acp registry generate: fetch %q: %s", source, response.Status)
	}
	raw, err := io.ReadAll(response.Body)
	if err != nil {
		return nil, fmt.Errorf("acp registry generate: read %q: %w", source, err)
	}
	return raw, nil
}

func render(registry registryDocument) ([]byte, int, error) {
	var body bytes.Buffer
	body.WriteString("// Code generated by go generate; DO NOT EDIT.\n\n")
	body.WriteString("package agentregistry\n\n")
	body.WriteString("var registeredNPXAgents = []registryNPXAgent{\n")
	count := 0
	for _, agent := range registry.Agents {
		if agent.Distribution.NPX == nil || strings.TrimSpace(agent.Distribution.NPX.Package) == "" {
			continue
		}
		count++
		body.WriteString("\t{\n")
		body.WriteString("\t\tAgent: ConnectableAgent{\n")
		fmt.Fprintf(&body, "\t\t\tID: %s, DisplayName: %s, Version: %s, RegistryID: %s,\n",
			quoted(productAgentID(agent.ID)),
			quoted(agent.Name),
			quoted(agent.Version),
			quoted(agent.ID),
		)
		fmt.Fprintf(&body, "\t\t\tDescription: %s,\n", quoted(agent.Description))
		body.WriteString("\t\t},\n")
		fmt.Fprintf(&body, "\t\tPackage: %s,\n", quoted(agent.Distribution.NPX.Package))
		if len(agent.Distribution.NPX.Args) > 0 {
			body.WriteString("\t\tArgs: []string{")
			for index, arg := range agent.Distribution.NPX.Args {
				if index > 0 {
					body.WriteString(", ")
				}
				body.WriteString(quoted(arg))
			}
			body.WriteString("},\n")
		}
		if len(agent.Distribution.NPX.Env) > 0 {
			keys := make([]string, 0, len(agent.Distribution.NPX.Env))
			for key := range agent.Distribution.NPX.Env {
				keys = append(keys, key)
			}
			sort.Strings(keys)
			body.WriteString("\t\tEnv: map[string]string{\n")
			for _, key := range keys {
				fmt.Fprintf(&body, "\t\t\t%s: %s,\n", quoted(key), quoted(agent.Distribution.NPX.Env[key]))
			}
			body.WriteString("\t\t},\n")
		}
		body.WriteString("\t},\n")
	}
	body.WriteString("}\n")
	formatted, err := format.Source(body.Bytes())
	if err != nil {
		return nil, 0, fmt.Errorf("acp registry generate: format output: %w", err)
	}
	return formatted, count, nil
}

func productAgentID(registryID string) string {
	switch strings.ToLower(strings.TrimSpace(registryID)) {
	case "codex-acp":
		return "codex"
	case "claude-acp":
		return "claude"
	case "github-copilot-cli":
		return "copilot"
	case "grok-build":
		return "grok"
	default:
		return strings.ToLower(strings.TrimSpace(registryID))
	}
}

func quoted(value string) string {
	return strconv.Quote(value)
}
