package modelcatalog

// catalogEntry maps a provider+model pattern to capabilities.
type catalogEntry struct {
	provider string // provider name (e.g. "deepseek", "openai")
	pattern  string // model name prefix or exact match (e.g. "deepseek-v4-flash", "gpt-4o")
	caps     ModelCapabilities
}

// builtinCatalog is the static registry of known model capabilities.
// Add new SOTA models here as they become available.
var builtinCatalog = []catalogEntry{
	// ── DeepSeek ──────────────────────────────────────────────────────────
	{
		provider: "deepseek",
		pattern:  "deepseek-v4-flash",
		caps: ModelCapabilities{
			ContextWindowTokens:    1048576,
			MaxOutputTokens:        393216,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeToggle,
			ReasoningEfforts:       []string{"high", "max"},
			DefaultReasoningEffort: "high",
			SupportsJSONOutput:     true,
			SupportsImages:         false,
		},
	},
	{
		provider: "deepseek",
		pattern:  "deepseek-v4-pro",
		caps: ModelCapabilities{
			ContextWindowTokens:    1048576,
			MaxOutputTokens:        393216,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeToggle,
			ReasoningEfforts:       []string{"high", "max"},
			DefaultReasoningEffort: "high",
			SupportsJSONOutput:     true,
			SupportsImages:         false,
		},
	},
	// ── OpenAI ────────────────────────────────────────────────────────────
	{
		provider: "openai",
		pattern:  "gpt-5.5",
		caps: ModelCapabilities{
			ContextWindowTokens:    1050000,
			MaxOutputTokens:        128000,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeEffort,
			ReasoningEfforts:       []string{"none", "low", "medium", "high", "xhigh"},
			DefaultReasoningEffort: "medium",
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "openai",
		pattern:  "gpt-5.5-pro",
		caps: ModelCapabilities{
			ContextWindowTokens:    1050000,
			MaxOutputTokens:        128000,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeEffort,
			ReasoningEfforts:       []string{"none", "low", "medium", "high", "xhigh"},
			DefaultReasoningEffort: "medium",
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "openai",
		pattern:  "gpt-5.5-instant",
		caps: ModelCapabilities{
			ContextWindowTokens:    400000,
			MaxOutputTokens:        128000,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeEffort,
			ReasoningEfforts:       []string{"none", "low", "medium", "high", "xhigh"},
			DefaultReasoningEffort: "medium",
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "openai",
		pattern:  "gpt-5.4",
		caps: ModelCapabilities{
			ContextWindowTokens:    1050000,
			MaxOutputTokens:        128000,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeEffort,
			ReasoningEfforts:       []string{"none", "low", "medium", "high", "xhigh"},
			DefaultReasoningEffort: "medium",
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "openai",
		pattern:  "gpt-5.4-pro",
		caps: ModelCapabilities{
			ContextWindowTokens:    1050000,
			MaxOutputTokens:        128000,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeEffort,
			ReasoningEfforts:       []string{"none", "low", "medium", "high", "xhigh"},
			DefaultReasoningEffort: "medium",
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "openai",
		pattern:  "gpt-5.4-mini",
		caps: ModelCapabilities{
			ContextWindowTokens:    400000,
			MaxOutputTokens:        128000,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeEffort,
			ReasoningEfforts:       []string{"none", "low", "medium", "high", "xhigh"},
			DefaultReasoningEffort: "medium",
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "openai",
		pattern:  "gpt-5.4-nano",
		caps: ModelCapabilities{
			ContextWindowTokens:    400000,
			MaxOutputTokens:        128000,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeEffort,
			ReasoningEfforts:       []string{"none", "low", "medium", "high", "xhigh"},
			DefaultReasoningEffort: "medium",
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "openai",
		pattern:  "gpt-4o",
		caps: ModelCapabilities{
			ContextWindowTokens:    128000,
			MaxOutputTokens:        16384,
			DefaultMaxOutputTokens: 4096,
			SupportsToolCalls:      true,
			SupportsReasoning:      false,
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "openai",
		pattern:  "gpt-4o-mini",
		caps: ModelCapabilities{
			ContextWindowTokens:    128000,
			MaxOutputTokens:        16384,
			DefaultMaxOutputTokens: 4096,
			SupportsToolCalls:      true,
			SupportsReasoning:      false,
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "openai",
		pattern:  "o1",
		caps: ModelCapabilities{
			ContextWindowTokens:    200000,
			MaxOutputTokens:        100000,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningEfforts:       []string{"low", "medium", "high"},
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "openai",
		pattern:  "o1-mini",
		caps: ModelCapabilities{
			ContextWindowTokens:    128000,
			MaxOutputTokens:        65536,
			DefaultMaxOutputTokens: 16384,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningEfforts:       []string{"low", "medium", "high"},
			SupportsJSONOutput:     true,
			SupportsImages:         false,
		},
	},
	{
		provider: "openai",
		pattern:  "o3",
		caps: ModelCapabilities{
			ContextWindowTokens:    200000,
			MaxOutputTokens:        100000,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningEfforts:       []string{"low", "medium", "high", "xhigh"},
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "openai",
		pattern:  "o3-mini",
		caps: ModelCapabilities{
			ContextWindowTokens:    200000,
			MaxOutputTokens:        100000,
			DefaultMaxOutputTokens: 16384,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningEfforts:       []string{"low", "medium", "high", "xhigh"},
			SupportsJSONOutput:     true,
			SupportsImages:         false,
		},
	},
	{
		provider: "openai",
		pattern:  "o4-mini",
		caps: ModelCapabilities{
			ContextWindowTokens:    200000,
			MaxOutputTokens:        100000,
			DefaultMaxOutputTokens: 16384,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningEfforts:       []string{"low", "medium", "high", "xhigh"},
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "openai",
		pattern:  "gpt-4.1",
		caps: ModelCapabilities{
			ContextWindowTokens:    1047576,
			MaxOutputTokens:        32768,
			DefaultMaxOutputTokens: 16384,
			SupportsToolCalls:      true,
			SupportsReasoning:      false,
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "openai",
		pattern:  "gpt-4.1-mini",
		caps: ModelCapabilities{
			ContextWindowTokens:    1047576,
			MaxOutputTokens:        32768,
			DefaultMaxOutputTokens: 16384,
			SupportsToolCalls:      true,
			SupportsReasoning:      false,
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "openai",
		pattern:  "gpt-4.1-nano",
		caps: ModelCapabilities{
			ContextWindowTokens:    1047576,
			MaxOutputTokens:        32768,
			DefaultMaxOutputTokens: 16384,
			SupportsToolCalls:      true,
			SupportsReasoning:      false,
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	// ── Anthropic ─────────────────────────────────────────────────────────
	{
		provider: "anthropic",
		pattern:  "claude-fable-5",
		caps: ModelCapabilities{
			ContextWindowTokens:    1000000,
			MaxOutputTokens:        128000,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeEffort,
			ReasoningEfforts:       []string{"low", "medium", "high"},
			DefaultReasoningEffort: "medium",
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "anthropic",
		pattern:  "claude-mythos-5",
		caps: ModelCapabilities{
			ContextWindowTokens:    1000000,
			MaxOutputTokens:        128000,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeEffort,
			ReasoningEfforts:       []string{"low", "medium", "high"},
			DefaultReasoningEffort: "medium",
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "anthropic",
		pattern:  "claude-opus-4-8",
		caps: ModelCapabilities{
			ContextWindowTokens:    1000000,
			MaxOutputTokens:        128000,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeEffort,
			ReasoningEfforts:       []string{"low", "medium", "high"},
			DefaultReasoningEffort: "high",
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "anthropic",
		pattern:  "claude-sonnet-4-6",
		caps: ModelCapabilities{
			ContextWindowTokens:    1000000,
			MaxOutputTokens:        64000,
			DefaultMaxOutputTokens: 16384,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeEffort,
			ReasoningEfforts:       []string{"low", "medium", "high"},
			DefaultReasoningEffort: "medium",
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "anthropic",
		pattern:  "claude-haiku-4-5",
		caps: ModelCapabilities{
			ContextWindowTokens:    200000,
			MaxOutputTokens:        64000,
			DefaultMaxOutputTokens: 16384,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeEffort,
			ReasoningEfforts:       []string{"low", "medium", "high"},
			DefaultReasoningEffort: "medium",
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "anthropic",
		pattern:  "claude-sonnet-4",
		caps: ModelCapabilities{
			ContextWindowTokens:    200000,
			MaxOutputTokens:        64000,
			DefaultMaxOutputTokens: 16384,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningEfforts:       []string{"low", "medium", "high"},
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "anthropic",
		pattern:  "claude-3-7-sonnet",
		caps: ModelCapabilities{
			ContextWindowTokens:    200000,
			MaxOutputTokens:        64000,
			DefaultMaxOutputTokens: 16384,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningEfforts:       []string{"low", "medium", "high"},
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "anthropic",
		pattern:  "claude-3-5-sonnet",
		caps: ModelCapabilities{
			ContextWindowTokens:    200000,
			MaxOutputTokens:        8192,
			DefaultMaxOutputTokens: 4096,
			SupportsToolCalls:      true,
			SupportsReasoning:      false,
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "anthropic",
		pattern:  "claude-3-5-haiku",
		caps: ModelCapabilities{
			ContextWindowTokens:    200000,
			MaxOutputTokens:        8192,
			DefaultMaxOutputTokens: 4096,
			SupportsToolCalls:      true,
			SupportsReasoning:      false,
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "anthropic",
		pattern:  "claude-opus-4",
		caps: ModelCapabilities{
			ContextWindowTokens:    200000,
			MaxOutputTokens:        64000,
			DefaultMaxOutputTokens: 16384,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningEfforts:       []string{"low", "medium", "high"},
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	// ── MiniMax (Anthropic-compatible) ───────────────────────────────────
	{
		provider: "minimax",
		pattern:  "MiniMax-M3",
		caps: ModelCapabilities{
			ContextWindowTokens:    1000000,
			MaxOutputTokens:        1000000,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeFixed,
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "minimax",
		pattern:  "MiniMax-M2.7",
		caps: ModelCapabilities{
			ContextWindowTokens:    204800,
			MaxOutputTokens:        131072,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeFixed,
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "minimax",
		pattern:  "MiniMax-M2.7-highspeed",
		caps: ModelCapabilities{
			ContextWindowTokens:    204800,
			MaxOutputTokens:        131072,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeFixed,
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "minimax",
		pattern:  "MiniMax-M2.5",
		caps: ModelCapabilities{
			ContextWindowTokens:    204800,
			MaxOutputTokens:        32768,
			DefaultMaxOutputTokens: 8192,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeFixed,
			SupportsJSONOutput:     true,
			SupportsImages:         false,
		},
	},
	{
		provider: "minimax",
		pattern:  "MiniMax-M2.5-highspeed",
		caps: ModelCapabilities{
			ContextWindowTokens:    204800,
			MaxOutputTokens:        32768,
			DefaultMaxOutputTokens: 8192,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeFixed,
			SupportsJSONOutput:     true,
			SupportsImages:         false,
		},
	},
	{
		provider: "minimax",
		pattern:  "MiniMax-M2.1",
		caps: ModelCapabilities{
			ContextWindowTokens:    204800,
			MaxOutputTokens:        32768,
			DefaultMaxOutputTokens: 8192,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeFixed,
			SupportsJSONOutput:     true,
			SupportsImages:         false,
		},
	},
	{
		provider: "minimax",
		pattern:  "MiniMax-M2.1-highspeed",
		caps: ModelCapabilities{
			ContextWindowTokens:    204800,
			MaxOutputTokens:        32768,
			DefaultMaxOutputTokens: 8192,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeFixed,
			SupportsJSONOutput:     true,
			SupportsImages:         false,
		},
	},
	{
		provider: "minimax",
		pattern:  "MiniMax-M2",
		caps: ModelCapabilities{
			ContextWindowTokens:    204800,
			MaxOutputTokens:        8192,
			DefaultMaxOutputTokens: 8192,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeFixed,
			SupportsJSONOutput:     true,
			SupportsImages:         false,
		},
	},
	// ── CodeFree ─────────────────────────────────────────────────────────
	{
		provider: "codefree",
		pattern:  "GLM-4.7",
		caps: ModelCapabilities{
			ContextWindowTokens:    128000,
			MaxOutputTokens:        8000,
			DefaultMaxOutputTokens: 8000,
			SupportsToolCalls:      true,
			ReasoningMode:          ReasoningModeNone,
			SupportsJSONOutput:     true,
			SupportsImages:         false,
		},
	},
	{
		provider: "codefree",
		pattern:  "DeepSeek-V3.1-Terminus",
		caps: ModelCapabilities{
			ContextWindowTokens:    128000,
			MaxOutputTokens:        8000,
			DefaultMaxOutputTokens: 8000,
			SupportsToolCalls:      true,
			ReasoningMode:          ReasoningModeNone,
			SupportsJSONOutput:     true,
			SupportsImages:         false,
		},
	},
	{
		provider: "codefree",
		pattern:  "Qwen3.5-122B-A10B",
		caps: ModelCapabilities{
			ContextWindowTokens:    128000,
			MaxOutputTokens:        8000,
			DefaultMaxOutputTokens: 8000,
			SupportsToolCalls:      true,
			ReasoningMode:          ReasoningModeNone,
			SupportsJSONOutput:     true,
			SupportsImages:         false,
		},
	},
	{
		provider: "codefree",
		pattern:  "GLM-5.1",
		caps: ModelCapabilities{
			ContextWindowTokens:    128000,
			MaxOutputTokens:        8000,
			DefaultMaxOutputTokens: 8000,
			SupportsToolCalls:      true,
			ReasoningMode:          ReasoningModeNone,
			SupportsJSONOutput:     true,
			SupportsImages:         false,
		},
	},
	// ── Gemini ────────────────────────────────────────────────────────────
	{
		provider: "gemini",
		pattern:  "gemini-3.5-flash",
		caps: ModelCapabilities{
			ContextWindowTokens:    1048576,
			MaxOutputTokens:        65536,
			DefaultMaxOutputTokens: 8192,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeEffort,
			ReasoningEfforts:       []string{"low", "medium", "high"},
			DefaultReasoningEffort: "medium",
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "gemini",
		pattern:  "gemini-3.1-pro-preview",
		caps: ModelCapabilities{
			ContextWindowTokens:    1048576,
			MaxOutputTokens:        65536,
			DefaultMaxOutputTokens: 8192,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeEffort,
			ReasoningEfforts:       []string{"low", "medium", "high"},
			DefaultReasoningEffort: "medium",
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "gemini",
		pattern:  "gemini-3.1-pro-preview-customtools",
		caps: ModelCapabilities{
			ContextWindowTokens:    1048576,
			MaxOutputTokens:        65536,
			DefaultMaxOutputTokens: 8192,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeEffort,
			ReasoningEfforts:       []string{"low", "medium", "high"},
			DefaultReasoningEffort: "medium",
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "gemini",
		pattern:  "gemini-3-flash-preview",
		caps: ModelCapabilities{
			ContextWindowTokens:    1048576,
			MaxOutputTokens:        65536,
			DefaultMaxOutputTokens: 8192,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeEffort,
			ReasoningEfforts:       []string{"low", "medium", "high"},
			DefaultReasoningEffort: "medium",
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "gemini",
		pattern:  "gemini-3.1-flash-lite",
		caps: ModelCapabilities{
			ContextWindowTokens:    1048576,
			MaxOutputTokens:        65536,
			DefaultMaxOutputTokens: 8192,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeEffort,
			ReasoningEfforts:       []string{"low", "medium", "high"},
			DefaultReasoningEffort: "medium",
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "gemini",
		pattern:  "gemini-2.5-pro",
		caps: ModelCapabilities{
			ContextWindowTokens:    1048576,
			MaxOutputTokens:        65536,
			DefaultMaxOutputTokens: 8192,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningEfforts:       []string{"low", "medium", "high"},
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "gemini",
		pattern:  "gemini-2.5-flash",
		caps: ModelCapabilities{
			ContextWindowTokens:    1048576,
			MaxOutputTokens:        65536,
			DefaultMaxOutputTokens: 8192,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningEfforts:       []string{"low", "medium", "high"},
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "gemini",
		pattern:  "gemini-2.0-flash",
		caps: ModelCapabilities{
			ContextWindowTokens:    1048576,
			MaxOutputTokens:        8192,
			DefaultMaxOutputTokens: 8192,
			SupportsToolCalls:      true,
			SupportsReasoning:      false,
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	// ── Mimo ──────────────────────────────────────────────────────────────
	{
		provider: "xiaomi",
		pattern:  "mimo-v2.5-pro",
		caps: ModelCapabilities{
			ContextWindowTokens:    1048576,
			MaxOutputTokens:        131072,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			SupportsJSONOutput:     true,
			SupportsImages:         false,
		},
	},
	{
		provider: "xiaomi",
		pattern:  "mimo-v2-pro",
		caps: ModelCapabilities{
			ContextWindowTokens:    1048576,
			MaxOutputTokens:        131072,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			SupportsJSONOutput:     true,
			SupportsImages:         false,
		},
	},
	{
		provider: "xiaomi",
		pattern:  "mimo-v2.5",
		caps: ModelCapabilities{
			ContextWindowTokens:    1048576,
			MaxOutputTokens:        131072,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "xiaomi",
		pattern:  "mimo-v2-omni",
		caps: ModelCapabilities{
			ContextWindowTokens:    262144,
			MaxOutputTokens:        131072,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "xiaomi",
		pattern:  "mimo-v2-flash",
		caps: ModelCapabilities{
			ContextWindowTokens:    262144,
			MaxOutputTokens:        65536,
			DefaultMaxOutputTokens: 16384,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			SupportsJSONOutput:     true,
			SupportsImages:         false,
		},
	},
	// ── Volcengine Coding Plan ────────────────────────────────────────────
	{
		provider: "volcengine",
		pattern:  "doubao-seed-1.8",
		caps: ModelCapabilities{
			ContextWindowTokens:    256000,
			MaxOutputTokens:        64000,
			DefaultMaxOutputTokens: 8192,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "volcengine",
		pattern:  "doubao-seed-2.0-code",
		caps: ModelCapabilities{
			ContextWindowTokens:    256000,
			MaxOutputTokens:        32000,
			DefaultMaxOutputTokens: 8192,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "volcengine",
		pattern:  "doubao-seed-2.0-pro",
		caps: ModelCapabilities{
			ContextWindowTokens:    256000,
			MaxOutputTokens:        64000,
			DefaultMaxOutputTokens: 8192,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "volcengine",
		pattern:  "doubao-seed-2.0-lite",
		caps: ModelCapabilities{
			ContextWindowTokens:    256000,
			MaxOutputTokens:        64000,
			DefaultMaxOutputTokens: 8192,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "volcengine",
		pattern:  "doubao-seed-2.0-mini",
		caps: ModelCapabilities{
			ContextWindowTokens:    256000,
			MaxOutputTokens:        64000,
			DefaultMaxOutputTokens: 8192,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "volcengine",
		pattern:  "doubao-seed-code",
		caps: ModelCapabilities{
			ContextWindowTokens:    256000,
			MaxOutputTokens:        64000,
			DefaultMaxOutputTokens: 8192,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "volcengine",
		pattern:  "minimax-m2.5",
		caps: ModelCapabilities{
			ContextWindowTokens:    128000,
			MaxOutputTokens:        32768,
			DefaultMaxOutputTokens: 8192,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			SupportsJSONOutput:     true,
		},
	},
	{
		provider: "volcengine",
		pattern:  "glm-4.7",
		caps: ModelCapabilities{
			ContextWindowTokens:    128000,
			MaxOutputTokens:        32768,
			DefaultMaxOutputTokens: 8192,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			SupportsJSONOutput:     true,
		},
	},
	{
		provider: "volcengine",
		pattern:  "deepseek-v3.2",
		caps: ModelCapabilities{
			ContextWindowTokens:    128000,
			MaxOutputTokens:        32768,
			DefaultMaxOutputTokens: 8192,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			SupportsJSONOutput:     true,
		},
	},
	{
		provider: "volcengine",
		pattern:  "kimi-k2.5",
		caps: ModelCapabilities{
			ContextWindowTokens:    128000,
			MaxOutputTokens:        32768,
			DefaultMaxOutputTokens: 8192,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			SupportsJSONOutput:     true,
		},
	},
	// ── Ollama local defaults ─────────────────────────────────────────────
	{
		provider: "ollama",
		pattern:  "qwen2.5:7b",
		caps: ModelCapabilities{
			ContextWindowTokens:    128000,
			MaxOutputTokens:        32768,
			DefaultMaxOutputTokens: 8192,
			SupportsToolCalls:      true,
			SupportsJSONOutput:     true,
		},
	},
	{
		provider: "ollama",
		pattern:  "llama3.1:8b",
		caps: ModelCapabilities{
			ContextWindowTokens:    128000,
			MaxOutputTokens:        32768,
			DefaultMaxOutputTokens: 8192,
			SupportsToolCalls:      true,
			SupportsJSONOutput:     true,
		},
	},
	{
		provider: "ollama",
		pattern:  "deepseek-r1:7b",
		caps: ModelCapabilities{
			ContextWindowTokens:    128000,
			MaxOutputTokens:        32768,
			DefaultMaxOutputTokens: 8192,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeToggle,
			SupportsJSONOutput:     true,
		},
	},
	{
		provider: "ollama",
		pattern:  "gemma3:4b",
		caps: ModelCapabilities{
			ContextWindowTokens:    128000,
			MaxOutputTokens:        32768,
			DefaultMaxOutputTokens: 8192,
			SupportsImages:         true,
			SupportsJSONOutput:     true,
		},
	},
}
