// Code generated by caelis-client-protocol-gen/v2.7.0 from api/control/v1/openapi.json; DO NOT EDIT.
export const generatorVersion = 'caelis-client-protocol-gen/v2.7.0' as const;
export const operationIds = ["cancelParticipant", "cancelSessionTurn", "closeSession", "compactSession", "completeFiles", "completeSessions", "completeSkills", "completeSlashArguments", "configureSessionControllerMode", "configureSessionMode", "configureSessionPresentation", "configureSessionPresentationMode", "createSession", "getAgentStatus", "getHostStatus", "getPresentationCapabilities", "getSessionPresentation", "getSessionState", "getSessionStatus", "getTerminalOutput", "handoffAgent", "hostAddMarketplace", "hostAddPluginPath", "hostApplyAgentBindingSet", "hostBindAgent", "hostCompleteFiles", "hostCompleteSessions", "hostCompleteSkills", "hostCompleteSlashArguments", "hostConnectACP", "hostConnectModel", "hostCreateAgentRole", "hostDeleteAgentBindingSet", "hostDeleteAgentRole", "hostDeleteModel", "hostDisablePlugin", "hostDisconnectACP", "hostEnablePlugin", "hostGetACPPreparation", "hostGetAgentBindingStatus", "hostGetAgentStatus", "hostInspectPlugin", "hostInstallPlugin", "hostListAgents", "hostListDisconnectCandidates", "hostListMarketplaces", "hostListPlugins", "hostPrepareACP", "hostPrepareACPAuthentication", "hostRemoveMarketplace", "hostRemovePlugin", "hostResetAgentBinding", "hostResolveSkill", "hostSaveAgentBindingSet", "hostUpdateMarketplace", "hostUseModel", "initializeClient", "inspectPlugin", "killTerminal", "listAgents", "listMarketplaces", "listParticipantHandles", "listPlugins", "listSessionTasks", "listSessions", "prepareSandbox", "promptParticipant", "promptSession", "readTaskEvents", "reconnectSession", "refreshSandbox", "releaseTerminal", "repairSandbox", "resetSandbox", "resolveApproval", "resolveSkill", "setSandboxBackend", "shutdownHost", "startParticipant", "steerSession", "subscribeTaskEvents", "useSessionModel", "waitTerminal", "watchSessionTaskDirectory"] as const;
export type OperationId = typeof operationIds[number];

export interface ACPAuthentication {
  method_id?: string;
  type?: ACPAuthenticationType;
}

export interface ACPAuthenticationChallengeMethod {
  description?: string;
  id: string;
  name?: string;
  type: ACPAuthenticationType;
}

export type ACPAuthenticationType = "agent" | "terminal";

export interface ACPAvailableCommandsUpdate {
  availableCommands: Array<AvailableCommand>;
  sessionUpdate: "available_commands_update";
}

export interface ACPCompactUpdate {
  _meta?: ACPMetadata;
  sessionUpdate: "compact";
}

export interface ACPConfigChoice {
  description?: string;
  name?: string;
  value?: string;
}

export interface ACPConfigOption {
  category?: string;
  current_value?: string;
  description?: string;
  id?: string;
  name?: string;
  options?: Array<ACPConfigChoice>;
  purpose?: ACPConfigOptionPurpose;
  type?: string;
}

export type ACPConfigOptionPurpose = "reasoning_effort";

export interface ACPConfigOptionUpdate {
  configOptions: Array<JSONObject>;
  sessionUpdate: "config_option_update";
}

export interface ACPConnection {
  authentication?: ACPAuthentication;
  id?: string;
  launcher?: ACPLauncher;
  name?: string;
}

export interface ACPContentChunk {
  _meta?: ACPMetadata;
  content: ContentBlock;
  messageId?: string;
  sessionUpdate: "user_message_chunk" | "agent_message_chunk" | "agent_thought_chunk" | "compact";
}

export interface ACPCurrentModeUpdate {
  currentModeId: string;
  sessionUpdate: "current_mode_update";
}

export interface ACPDiscoverySnapshot {
  authentication?: ACPAuthentication;
  config_options?: Array<ACPConfigOption>;
  connection_id?: string;
  current_model_id?: string;
  cwd?: string;
  discovered_at?: string;
  launch_fingerprint?: string;
  model_control?: ACPModelControl;
  models?: Array<ACPRemoteModel>;
  protocol_version?: number;
  selected_model_id?: string;
}

export type ACPLaunchKind = "executable" | "package_exec" | "managed";

export interface ACPLauncher {
  args?: Array<string>;
  command?: string;
  env?: Record<string, JSONValue>;
  kind?: ACPLaunchKind;
  work_dir?: string;
}

export type ACPLauncherChoice = "npx" | "global" | "managed" | "installed" | "command";

export interface ACPMetadata {
  caelis?: CaelisMetadata;
  compact?: CompactMetadata;
  from?: HandoffBindingMetadata;
  to?: HandoffBindingMetadata;
  [key: string]: JSONValue;
}

export interface ACPModelControl {
  config_id?: string;
  kind?: ACPModelControlKind;
}

export type ACPModelControlKind = "config_option" | "set_model";

export interface ACPPlanUpdate {
  entries: Array<PlanEntry>;
  sessionUpdate: "plan";
}

export interface ACPPreparation {
  authentication_methods?: Array<ACPAuthenticationChallengeMethod>;
  cleanup_warning?: string;
  connection?: ACPConnection;
  content_digest: string;
  created_at: string;
  discovery?: ACPDiscoverySnapshot;
  expires_at: string;
  observed_revision: Uint64Decimal;
  parent_ref?: string;
  ref: string;
  request: ACPPrepareRequest;
  selected_authentication?: ACPAuthentication;
  state: "planned" | "needs_auth" | "ready";
}

export interface ACPPreparationRequest {
  ref: string;
}

export interface ACPPrepareRequest {
  adapter_id?: string;
  command_line?: string;
  cwd?: string;
  launcher?: ACPLauncherChoice;
  model_id?: string;
  parent_ref?: string;
}

export interface ACPRawUpdate {
  sessionUpdate: string;
  [key: string]: JSONValue;
}

export interface ACPRemoteModel {
  description?: string;
  id?: string;
  name?: string;
}

export interface ACPSessionInfoUpdate {
  sessionUpdate: "session_info_update";
  title?: string;
  updatedAt?: string;
}

export interface ACPToolCall {
  _meta?: ACPMetadata;
  content?: Array<ToolCallContent>;
  kind?: string;
  locations?: Array<ToolCallLocation>;
  rawInput?: JSONValue;
  rawOutput?: JSONValue;
  sessionUpdate: "tool_call";
  status?: string;
  title: string;
  toolCallId: string;
}

export interface ACPToolCallUpdate {
  _meta?: ACPMetadata;
  content?: Array<ToolCallContent>;
  kind?: string;
  locations?: Array<ToolCallLocation>;
  rawInput?: JSONValue;
  rawOutput?: JSONValue;
  sessionUpdate: "tool_call_update";
  status?: string;
  title?: string;
  toolCallId: string;
}

export type ACPUpdate = ACPContentChunk | ACPToolCall | ACPToolCallUpdate | ACPPlanUpdate | ACPUsageUpdate | ACPCurrentModeUpdate | ACPConfigOptionUpdate | ACPSessionInfoUpdate | ACPAvailableCommandsUpdate | ACPRawUpdate;

export interface ACPUsageUpdate {
  _meta?: ACPMetadata;
  cost?: UsageCost;
  sessionUpdate: "usage_update";
  size: Uint64Decimal;
  used: Uint64Decimal;
}

export interface ActiveApproval {
  parent_tool?: ParentToolRelation;
  participant_id?: string;
  permission: JSONObject;
  request_id: string;
  scope?: "main" | "participant" | "subagent";
  scope_id?: string;
}

export interface ActorIdentity {
  id?: string;
  kind?: string;
  name?: string;
  role?: string;
}

export interface AddMarketplaceRequest {
  expected_controller_epoch?: string;
  expected_revision?: Uint64Decimal;
  operation_id?: string;
  session_id?: string;
  source: string;
}

export interface AddPluginPathRequest {
  expected_controller_epoch?: string;
  expected_revision?: Uint64Decimal;
  operation_id?: string;
  path: string;
  session_id?: string;
}

export interface AgentBindingSetRequest {
  expected_controller_epoch?: string;
  expected_revision?: Uint64Decimal;
  operation_id?: string;
  session_id?: string;
  set_name: string;
}

export type AgentBindingStatus = Record<string, JSONValue>;

export interface AgentCandidate {
  description?: string;
  name: string;
}

export type AgentCandidateList = Array<AgentCandidate>;

export interface AgentCommunication {
  source: ActorIdentity;
  text: string;
}

export interface AgentCommunicationEnvelope {
  _meta?: ACPMetadata;
  activity_id?: string;
  actor?: string;
  agent_communication: AgentCommunication;
  cursor: string;
  delivery: Delivery;
  event_id?: string;
  final?: boolean;
  handle_id?: string;
  kind: "caelis/agent_communication";
  occurred_at?: string;
  parent_tool?: ParentToolRelation;
  participant_id?: string;
  position: FeedPosition;
  projection_id?: string;
  run_id?: string;
  scope?: "main" | "participant" | "subagent";
  scope_id?: string;
  session_id?: string;
  turn_id?: string;
}

export interface AgentParticipantSnapshot {
  agent_name?: string;
  id: string;
  kind?: string;
  label?: string;
  role?: string;
  session_id?: string;
  source?: string;
}

export interface AgentRequest {
  limit?: number;
  session_id?: string;
  surface?: string;
}

export interface AgentStatusSnapshot {
  active_turn_kind?: string;
  available_agents?: AgentCandidateList;
  controller_commands?: Array<string>;
  controller_efforts?: SlashArgCandidateList;
  controller_epoch?: string;
  controller_kind?: string;
  controller_label?: string;
  controller_model?: string;
  controller_models?: SlashArgCandidateList;
  controller_reasoning_effort?: string;
  delegated_participants?: Array<AgentParticipantSnapshot>;
  has_active_turn?: boolean;
  participants?: Array<AgentParticipantSnapshot>;
  session_id?: string;
}

export interface ApprovalReview {
  authorization?: string;
  raw_input?: JSONObject;
  risk?: string;
  status?: string;
  text?: string;
  tool_call_id?: string;
  tool_name?: string;
}

export interface ApprovalReviewEnvelope {
  _meta?: ACPMetadata;
  activity_id?: string;
  actor?: string;
  approval_review: ApprovalReview;
  cursor: string;
  delivery: Delivery;
  event_id?: string;
  final?: boolean;
  handle_id?: string;
  kind: "caelis/approval_review";
  occurred_at?: string;
  parent_tool?: ParentToolRelation;
  participant_id?: string;
  position: FeedPosition;
  projection_id?: string;
  run_id?: string;
  scope?: "main" | "participant" | "subagent";
  scope_id?: string;
  session_id?: string;
  turn_id?: string;
}

export interface ApprovalState {
  active?: ActiveApproval;
  queued_count?: number;
}

export interface AudioContent {
  data: string;
  mimeType: string;
  type: "audio";
}

export interface AvailableCommand {
  description?: string;
  input?: JSONObject;
  name: string;
}

export interface BindAgentBindingRequest {
  binding: JSONObject;
  expected_controller_epoch?: string;
  expected_revision?: Uint64Decimal;
  operation_id?: string;
  session_id?: string;
}

export interface CaelisMetadata {
  runtime?: CaelisRuntimeMetadata;
  sdk?: SDKMetadata;
  usage?: UsageMetadata;
  [key: string]: JSONValue;
}

export interface CaelisRuntimeMetadata {
  stream?: RuntimeStreamMetadata;
  task?: RuntimeTaskMetadata;
  [key: string]: JSONValue;
}

export interface CancelParticipantRequest {
  expected_controller_epoch?: string;
  expected_revision?: Uint64Decimal;
  operation_id?: string;
  participant_id: string;
  reason?: string;
  session_id?: string;
  target: TurnTarget;
}

export interface CancelRequest {
  expected_controller_epoch?: string;
  expected_revision?: Uint64Decimal;
  operation_id?: string;
  reason?: string;
  session_id?: string;
  target: TurnTarget;
}

export interface ClientCapabilities {
  caelis_terminal_stream: true;
  client_managed_terminal: false;
  goal_bootstrap_supported: false;
  manage_loop_bootstrap_supported: false;
}

export interface CloseSessionRequest {
  expected_controller_epoch?: string;
  expected_revision?: Uint64Decimal;
  operation_id?: string;
  session_id?: string;
}

export interface CommandResource {
  digest?: string;
  kind?: string;
  ref?: string;
}

export interface CommandResult {
  detail?: string;
  error_code?: ErrorCode;
  error_kind?: ErrorKind;
  operation_id: string;
  outcome: Outcome;
  resource?: CommandResource;
  revision?: Uint64Decimal;
  session_id?: string;
  target?: CommandTarget;
}

export interface CommandTarget {
  handle_id?: string;
  run_id?: string;
  turn_id?: string;
}

export interface CompactMetadata {
  context_window_tokens?: Uint64Decimal;
  contract_version?: Uint64Decimal;
  revision?: Uint64Decimal;
  source_event_count?: Uint64Decimal;
  summarized_through_seq?: Uint64Decimal;
  total_tokens?: Uint64Decimal;
  [key: string]: JSONValue;
}

export interface CompactSessionRequest {
  expected_controller_epoch?: string;
  expected_revision?: Uint64Decimal;
  operation_id?: string;
  session_id?: string;
}

export interface CompletionCandidate {
  detail?: string;
  display?: string;
  kind?: string;
  path?: string;
  value: string;
}

export type CompletionCandidateList = Array<CompletionCandidate>;

export interface CompletionRequest {
  command?: string;
  cwd?: string;
  limit?: number;
  name?: string;
  query?: string;
  session_id?: string;
  surface?: string;
  workspace_key?: string;
}

export interface ConnectACPRequest {
  config_values?: Record<string, JSONValue>;
  expected_controller_epoch?: string;
  expected_revision?: Uint64Decimal;
  operation_id?: string;
  preparation_digest: string;
  preparation_ref: string;
  session_id?: string;
}

export interface ConnectConfig {
  api_key?: string;
  auth_type?: string;
  base_url?: string;
  context_window_tokens?: number;
  endpoint_id?: string;
  image_input?: boolean;
  max_output_tokens?: number;
  model: string;
  provider: string;
  reasoning_effort?: string;
  reasoning_levels?: Array<string>;
  stream_first_event_timeout_seconds?: number;
  timeout_seconds?: number;
}

export interface ConnectModelRequest {
  config: ConnectConfig;
  expected_controller_epoch?: string;
  expected_revision?: Uint64Decimal;
  operation_id?: string;
  session_id?: string;
}

export type ContentBlock = TextContent | ImageContent | AudioContent | ResourceContent;

export interface ControllerBinding {
  agent_name?: string;
  attached_at?: string;
  context_sync_seq?: Uint64Decimal;
  controller_id?: string;
  epoch_id?: string;
  kind?: ControllerKind;
  label?: string;
  remote_session_id?: string;
  source?: string;
}

export type ControllerKind = "kernel" | "acp";

export interface CreateAgentRoleRequest {
  binding?: JSONObject;
  expected_controller_epoch?: string;
  expected_revision?: Uint64Decimal;
  operation_id?: string;
  role: JSONObject;
  session_id?: string;
}

export interface CreateSessionRequest {
  cwd?: string;
  expected_controller_epoch?: string;
  expected_revision?: Uint64Decimal;
  metadata?: JSONObject;
  operation_id?: string;
  preferred_session_id?: string;
  session_id?: string;
  title?: string;
  workspace_key?: string;
}

export interface DeleteAgentRoleRequest {
  expected_controller_epoch?: string;
  expected_revision?: Uint64Decimal;
  handle: string;
  operation_id?: string;
  session_id?: string;
}

export interface DeleteModelRequest {
  expected_controller_epoch?: string;
  expected_revision?: Uint64Decimal;
  model: string;
  operation_id?: string;
  session_id?: string;
}

export interface Delivery {
  mode: DeliveryMode;
}

export type DeliveryMode = "canonical" | "mirror" | "transient";

export interface DisablePluginRequest {
  expected_controller_epoch?: string;
  expected_revision?: Uint64Decimal;
  id: string;
  operation_id?: string;
  session_id?: string;
}

export interface DisconnectACPRequest {
  agent_id: string;
  expected_controller_epoch?: string;
  expected_revision?: Uint64Decimal;
  operation_id?: string;
  session_id?: string;
}

export interface DisconnectCandidate {
  agent_id?: string;
  connection_id?: string;
  last_on_connection?: boolean;
  name?: string;
  sibling_count?: number;
}

export type DisconnectCandidateList = Array<DisconnectCandidate>;

export interface DisconnectCandidatesSnapshot {
  candidates: DisconnectCandidateList;
  revision: Uint64Decimal;
}

export interface DurableFeedPosition {
  projection_index: number;
  seq: Uint64Decimal;
}

export type EmptyResult = {  };

export interface EnablePluginRequest {
  expected_controller_epoch?: string;
  expected_revision?: Uint64Decimal;
  id: string;
  operation_id?: string;
  session_id?: string;
}

export type Envelope = SessionUpdateEnvelope | RequestPermissionEnvelope | NoticeEnvelope | ParticipantEnvelope | LifecycleEnvelope | AgentCommunicationEnvelope | ApprovalReviewEnvelope | ErrorEnvelope;

export interface EnvelopeBase {
  _meta?: ACPMetadata;
  activity_id?: string;
  actor?: string;
  cursor: string;
  delivery: Delivery;
  event_id?: string;
  final?: boolean;
  handle_id?: string;
  kind: EnvelopeKind;
  occurred_at?: string;
  parent_tool?: ParentToolRelation;
  participant_id?: string;
  position: FeedPosition;
  projection_id?: string;
  run_id?: string;
  scope?: "main" | "participant" | "subagent";
  scope_id?: string;
  session_id?: string;
  turn_id?: string;
}

export type EnvelopeKind = "session/update" | "session/request_permission" | "caelis/notice" | "caelis/participant" | "caelis/lifecycle" | "caelis/agent_communication" | "caelis/approval_review" | "caelis/error";

export type ErrorCode = "unknown" | "invalid_argument" | "not_found" | "already_exists" | "conflict" | "permission_denied" | "unauthenticated" | "failed_precondition" | "resource_exhausted" | "rate_limited" | "overloaded" | "timeout" | "cancelled" | "interrupted" | "unavailable" | "unsupported" | "unknown_outcome" | "internal";

export interface ErrorEnvelope {
  _meta?: ACPMetadata;
  activity_id?: string;
  actor?: string;
  cursor: string;
  delivery: Delivery;
  error: string;
  event_id?: string;
  final?: boolean;
  handle_id?: string;
  kind: "caelis/error";
  occurred_at?: string;
  parent_tool?: ParentToolRelation;
  participant_id?: string;
  position: FeedPosition;
  projection_id?: string;
  run_id?: string;
  scope?: "main" | "participant" | "subagent";
  scope_id?: string;
  session_id?: string;
  turn_id?: string;
}

export type ErrorKind = "session_closed" | "unauthorized" | "operation_conflict" | "state_revision_conflict";

export interface ErrorResponse {
  code: ErrorCode;
  error: string;
  kind?: ErrorKind;
}

export type FeedPosition = { durable: DurableFeedPosition } | { transient: TransientFeedPosition };

export interface HandoffAgentRequest {
  expected_controller_epoch?: string;
  expected_revision?: Uint64Decimal;
  operation_id?: string;
  session_id?: string;
  target: string;
}

export interface HandoffBindingMetadata {
  context_sync_seq?: Uint64Decimal;
  [key: string]: JSONValue;
}

export interface HostStatus {
  instance_id: string;
  ready: boolean;
  server_id: string;
}

export interface ImageContent {
  data: string;
  mimeType: string;
  type: "image";
}

export interface InstallPluginRequest {
  expected_controller_epoch?: string;
  expected_revision?: Uint64Decimal;
  operation_id?: string;
  session_id?: string;
  source: string;
}

export type JSONObject = Record<string, JSONValue>;

export type JSONValue = unknown;

export interface LifecycleEnvelope {
  _meta?: ACPMetadata;
  activity_id?: string;
  actor?: string;
  cursor: string;
  delivery: Delivery;
  event_id?: string;
  final?: boolean;
  handle_id?: string;
  kind: "caelis/lifecycle";
  lifecycle: LifecycleEvent;
  occurred_at?: string;
  parent_tool?: ParentToolRelation;
  participant_id?: string;
  position: FeedPosition;
  projection_id?: string;
  run_id?: string;
  scope?: "main" | "participant" | "subagent";
  scope_id?: string;
  session_id?: string;
  turn_id?: string;
}

export interface LifecycleEvent {
  reason?: string;
  state: string;
  stopReason?: string;
}

export interface MCPServerSnapshot {
  name: string;
  status: string;
  tools?: Array<string>;
  warning?: string;
}

export interface MarketplaceSnapshot {
  allow_cross_marketplace_dependencies?: Array<string>;
  description?: string;
  name: string;
  owner?: string;
  plugin_count?: number;
  plugin_root?: string;
  root?: string;
  source?: string;
  version?: string;
}

export type MarketplaceSnapshotList = Array<MarketplaceSnapshot>;

export interface ModelUsageSnapshot {
  model?: string;
  provider?: string;
  usage: UsageSnapshot;
}

export interface NoticeEnvelope {
  _meta?: ACPMetadata;
  activity_id?: string;
  actor?: string;
  cursor: string;
  delivery: Delivery;
  event_id?: string;
  final?: boolean;
  handle_id?: string;
  kind: "caelis/notice";
  notice: string;
  notice_kind?: NoticeKind;
  occurred_at?: string;
  parent_tool?: ParentToolRelation;
  participant_id?: string;
  position: FeedPosition;
  projection_id?: string;
  run_id?: string;
  scope?: "main" | "participant" | "subagent";
  scope_id?: string;
  session_id?: string;
  turn_id?: string;
}

export type NoticeKind = "compact" | "compact_failed";

export type Outcome = "accepted" | "committed" | "conflicted" | "rejected" | "unknown";

export interface ParentToolRelation {
  tool_call_id?: string;
  tool_name?: string;
}

export interface ParticipantBinding {
  agent_name?: string;
  attached_at?: string;
  attachment_generation?: string;
  context_sync_seq?: Uint64Decimal;
  controller_ref?: string;
  delegation_id?: string;
  id?: string;
  kind?: ParticipantKind;
  label?: string;
  parent_turn_id?: string;
  role?: ParticipantRole;
  session_id?: string;
  source?: string;
}

export interface ParticipantEnvelope {
  _meta?: ACPMetadata;
  activity_id?: string;
  actor?: string;
  cursor: string;
  delivery: Delivery;
  event_id?: string;
  final?: boolean;
  handle_id?: string;
  kind: "caelis/participant";
  occurred_at?: string;
  parent_tool?: ParentToolRelation;
  participant: ParticipantEvent;
  participant_id?: string;
  position: FeedPosition;
  projection_id?: string;
  run_id?: string;
  scope?: "main" | "participant" | "subagent";
  scope_id?: string;
  session_id?: string;
  turn_id?: string;
}

export interface ParticipantEvent {
  state: string;
}

export type ParticipantKind = "acp" | "subagent";

export type ParticipantRole = "sidecar" | "delegated" | "observer";

export interface PermissionOption {
  _meta?: ACPMetadata;
  kind: string;
  name: string;
  optionId: string;
}

export interface PlanEntry {
  content: string;
  priority: string;
  status: string;
}

export interface PluginRequest {
  id?: string;
  name?: string;
  path?: string;
  session_id?: string;
  source?: string;
  surface?: string;
}

export interface PluginSnapshot {
  agents?: Array<string>;
  description: string;
  enabled: boolean;
  hooks: Array<string>;
  id: string;
  mcp_servers?: Array<MCPServerSnapshot>;
  name: string;
  root: string;
  skills: Array<string>;
  status: string;
  version: string;
  warning?: string;
}

export type PluginSnapshotList = Array<PluginSnapshot>;

export type PositiveUint64Decimal = string;

export interface PrepareACPAuthenticationRequest {
  expected_controller_epoch?: string;
  expected_revision?: Uint64Decimal;
  method_id: string;
  operation_id?: string;
  preparation_digest: string;
  preparation_ref: string;
  session_id?: string;
}

export interface PrepareACPRequest {
  expected_controller_epoch?: string;
  expected_revision?: Uint64Decimal;
  operation_id?: string;
  request: ACPPrepareRequest;
  session_id?: string;
}

export interface PresentationCapabilities {
  audio: boolean;
  embedded_context: boolean;
  image: boolean;
}

export interface PresentationCommand {
  description?: string;
  input?: PresentationCommandInput;
  name: string;
}

export interface PresentationCommandInput {
  hint?: string;
}

export interface PresentationConfigOption {
  category?: string;
  current_value: JSONValue;
  description?: string;
  id: string;
  name: string;
  options?: Array<PresentationSelectOption>;
  type: string;
}

export type PresentationConfigOptionList = Array<PresentationConfigOption>;

export interface PresentationMode {
  description?: string;
  id: string;
  name: string;
}

export interface PresentationModeState {
  available_modes: Array<PresentationMode>;
  current_mode_id: string;
  target?: "approval" | "app" | "controller";
}

export interface PresentationModel {
  description?: string;
  id: string;
  name: string;
}

export interface PresentationModelState {
  available_models: Array<PresentationModel>;
  current_model_id: string;
}

export interface PresentationSelectOption {
  description?: string;
  name: string;
  value: string;
}

export interface PresentationSnapshot {
  commands?: Array<PresentationCommand>;
  config_options?: PresentationConfigOptionList;
  models?: PresentationModelState;
  modes?: PresentationModeState;
}

export type PromptContentPart = PromptTextContentPart | PromptImageContentPart;

export interface PromptImageContentPart {
  data: string;
  file_name?: string;
  mime_type: string;
  type: "image";
}

export interface PromptParticipantRequest {
  content_parts?: Array<PromptContentPart>;
  display_address?: string;
  display_input?: string;
  display_title?: string;
  expected_controller_epoch?: string;
  expected_revision?: Uint64Decimal;
  input?: string;
  operation_id?: string;
  participant_id: string;
  session_id?: string;
  source?: string;
}

export interface PromptRequest {
  content_parts?: Array<PromptContentPart>;
  display_input?: string;
  expected_controller_epoch?: string;
  expected_revision?: Uint64Decimal;
  input?: string;
  operation_id?: string;
  session_id?: string;
}

export interface PromptTextContentPart {
  text: string;
  type: "text";
}

export interface RemoveMarketplaceRequest {
  expected_controller_epoch?: string;
  expected_revision?: Uint64Decimal;
  name: string;
  operation_id?: string;
  session_id?: string;
}

export interface RemovePluginRequest {
  expected_controller_epoch?: string;
  expected_revision?: Uint64Decimal;
  id: string;
  operation_id?: string;
  session_id?: string;
}

export interface RequestPermission {
  _meta?: ACPMetadata;
  options: Array<PermissionOption>;
  sessionId: string;
  toolCall: ACPToolCallUpdate;
}

export interface RequestPermissionEnvelope {
  _meta?: ACPMetadata;
  activity_id?: string;
  actor?: string;
  approval_request_id: string;
  cursor: string;
  delivery: Delivery;
  event_id?: string;
  final?: boolean;
  handle_id?: string;
  kind: "session/request_permission";
  occurred_at?: string;
  parent_tool?: ParentToolRelation;
  participant_id?: string;
  permission: RequestPermission;
  position: FeedPosition;
  projection_id?: string;
  run_id?: string;
  scope?: "main" | "participant" | "subagent";
  scope_id?: string;
  session_id?: string;
  turn_id?: string;
}

export interface ResetAgentBindingRequest {
  expected_controller_epoch?: string;
  expected_revision?: Uint64Decimal;
  handle: string;
  operation_id?: string;
  session_id?: string;
}

export interface ResolveApprovalRequest {
  approval_request_id: string;
  approved: boolean;
  expected_controller_epoch?: string;
  expected_revision?: Uint64Decimal;
  operation_id?: string;
  option_id?: string;
  outcome: string;
  reason?: string;
  review_text?: string;
  session_id?: string;
  target: TurnTarget;
}

export interface ResourceContent {
  mimeType?: string;
  name?: string;
  type: "resource";
  uri: string;
}

export interface ResumeCandidate {
  age?: string;
  model?: string;
  prompt?: string;
  session_id: string;
  title?: string;
  updated_at?: string;
  workspace?: string;
}

export type ResumeCandidateList = Array<ResumeCandidate>;

export type ResumeMode = "exact" | "durable_fallback";

export interface RunState {
  active?: boolean;
  handle_id?: string;
  kind?: string;
  run_id?: string;
  started_at?: string;
  status?: string;
  turn_id?: string;
  waiting_approval?: boolean;
}

export interface RuntimeStreamMetadata {
  truncated_before?: Uint64Decimal;
  [key: string]: JSONValue;
}

export interface RuntimeTaskMetadata {
  event_cursor?: Uint64Decimal;
  output_cursor?: Uint64Decimal;
  turn_seq?: Uint64Decimal;
  [key: string]: JSONValue;
}

export interface SDKMetadata {
  context_window_tokens?: Uint64Decimal;
  usage?: SDKUsageMetadata;
  [key: string]: JSONValue;
}

export interface SDKUsageMetadata {
  cached_input_tokens?: Uint64Decimal;
  completion_tokens?: Uint64Decimal;
  context_window_tokens?: Uint64Decimal;
  cost_micros?: Uint64Decimal;
  prompt_tokens?: Uint64Decimal;
  reasoning_tokens?: Uint64Decimal;
  total_tokens?: Uint64Decimal;
  [key: string]: JSONValue;
}

export interface SandboxRequest {
  backend?: string;
  expected_controller_epoch?: string;
  expected_revision?: Uint64Decimal;
  operation_id?: string;
  session_id?: string;
}

export interface SandboxSetupCheck {
  counts?: Record<string, JSONValue>;
  current?: boolean;
  details?: Record<string, JSONValue>;
  error?: string;
  name?: string;
  reason?: string;
  required?: boolean;
  root?: string;
  scope?: string;
  updated_at?: string;
  version?: number;
}

export interface SandboxSetupStatus {
  checks?: Array<SandboxSetupCheck>;
  counts?: Record<string, JSONValue>;
  details?: Record<string, JSONValue>;
  error?: string;
  required?: boolean;
}

export interface ServerInfo {
  api_version: string;
  build_id?: string;
  build_kind?: "dev" | "release";
  capabilities?: Array<string>;
  distribution_version?: string;
  envelope_version: string;
  instance_id?: string;
  protocol_version: number;
  server_id?: string;
  transports?: Array<string>;
}

export interface SessionControllerModeRequest {
  expected_controller_epoch?: string;
  expected_revision?: Uint64Decimal;
  mode: string;
  operation_id?: string;
  session_id?: string;
}

export interface SessionList {
  next_cursor?: string;
  sessions?: Array<SessionSummary>;
}

export interface SessionModeRequest {
  expected_controller_epoch?: string;
  expected_revision?: Uint64Decimal;
  mode: string;
  operation_id?: string;
  session_id?: string;
}

export interface SessionModelRequest {
  expected_controller_epoch?: string;
  expected_revision?: Uint64Decimal;
  model: string;
  operation_id?: string;
  reasoning_effort?: string;
  session_id?: string;
}

export interface SessionPresentationConfigRequest {
  config_id: string;
  expected_controller_epoch?: string;
  expected_revision?: Uint64Decimal;
  operation_id?: string;
  session_id?: string;
  value: string;
}

export interface SessionPresentationModeRequest {
  expected_controller_epoch?: string;
  expected_revision?: Uint64Decimal;
  mode: string;
  operation_id?: string;
  session_id?: string;
}

export interface SessionRef {
  app_name?: string;
  session_id?: string;
  user_id?: string;
  workspace_key?: string;
}

export interface SessionState {
  api_version: string;
  approval: ApprovalState;
  boundary_cursor?: string;
  boundary_position?: FeedPosition;
  capabilities: ClientCapabilities;
  controller: ControllerBinding;
  cwd?: string;
  envelope_version: string;
  metadata?: JSONObject;
  participants?: Array<ParticipantBinding>;
  protocol_version: number;
  resume_mode: ResumeMode;
  revision: Uint64Decimal;
  run: RunState;
  session_id: string;
  title?: string;
  transient_gap?: boolean;
  workspace_key?: string;
}

export interface SessionSummary {
  app_name?: string;
  cwd?: string;
  metadata?: JSONObject;
  session_id?: string;
  title?: string;
  updated_at?: string;
  user_id?: string;
  workspace_key?: string;
}

export interface SessionUpdateEnvelope {
  _meta?: ACPMetadata;
  activity_id?: string;
  actor?: string;
  cursor: string;
  delivery: Delivery;
  event_id?: string;
  final?: boolean;
  handle_id?: string;
  kind: "session/update";
  occurred_at?: string;
  parent_tool?: ParentToolRelation;
  participant_id?: string;
  position: FeedPosition;
  projection_id?: string;
  run_id?: string;
  scope?: "main" | "participant" | "subagent";
  scope_id?: string;
  session_id?: string;
  turn_id?: string;
  update: ACPUpdate;
}

export interface SkillResolveResult {
  canonical?: string;
  matches?: Array<string>;
}

export interface SlashArgCandidate {
  detail?: string;
  display?: string;
  model_image_input_known?: boolean;
  model_metadata_complete?: boolean;
  no_auth?: boolean;
  value: string;
}

export type SlashArgCandidateList = Array<SlashArgCandidate>;

export interface StartParticipantRequest {
  content_parts?: Array<PromptContentPart>;
  detach_source?: string;
  display_address?: string;
  display_input?: string;
  display_title?: string;
  expected_controller_epoch?: string;
  expected_revision?: Uint64Decimal;
  handle: string;
  input?: string;
  label?: string;
  operation_id?: string;
  role?: ParticipantRole;
  session_id?: string;
  source?: string;
  transient?: boolean;
}

export interface StatusConfiguration {
  revision: Uint64Decimal;
}

export interface StatusDiagnostics {
  config_dir_mode?: string;
  config_dir_secure?: boolean;
  config_file_mode?: string;
  config_file_secure?: boolean;
  config_path?: string;
  config_permissions_secure?: boolean;
  go_version?: string;
  goarch?: string;
  goos?: string;
  persisted_plaintext_token?: boolean;
  token_source?: string;
  warnings?: Array<string>;
}

export interface StatusModel {
  alias?: string;
  display?: string;
  missing_api_key?: boolean;
  name?: string;
  provider?: string;
  reasoning_effort?: string;
}

export interface StatusRateLimit {
  id?: string;
  name?: string;
  windows?: Array<StatusRateLimitWindow>;
}

export interface StatusRateLimitWindow {
  duration_minutes?: number;
  kind?: string;
  label?: string;
  resets_at?: string;
  used_percent?: number;
}

export interface StatusRateLimits {
  captured_at?: string;
  limits?: Array<StatusRateLimit>;
  plan?: string;
  provider?: string;
}

export interface StatusRuntime {
  active_jobs?: number;
  active_sessions?: Array<string>;
  active_turn_kind?: string;
  running?: boolean;
}

export interface StatusSandbox {
  fallback_reason?: string;
  full_access_mode?: boolean;
  host_execution?: boolean;
  install_hint?: string;
  requested_backend?: string;
  resolved_backend?: string;
  route?: string;
  security_summary?: string;
  setup: SandboxSetupStatus;
  type?: string;
}

export interface StatusSession {
  id?: string;
  mode_label?: string;
  policy_profile?: string;
  session_mode?: string;
  store_dir?: string;
  surface?: string;
  workspace?: string;
}

export interface StatusSnapshot {
  configuration: StatusConfiguration;
  diagnostics: StatusDiagnostics;
  model_status: StatusModel;
  rate_limits: StatusRateLimits;
  runtime: StatusRuntime;
  sandbox_status: StatusSandbox;
  session: StatusSession;
  usage: StatusUsage;
}

export interface StatusUsage {
  completion_tokens?: number;
  context_window_tokens?: number;
  prompt_tokens?: number;
  session_usage_by_model?: Array<ModelUsageSnapshot>;
  session_usage_total: UsageSnapshot;
  total_tokens?: number;
}

export interface SteerRequest {
  content_parts?: Array<PromptContentPart>;
  display_input?: string;
  expected_controller_epoch?: string;
  expected_revision?: Uint64Decimal;
  input?: string;
  operation_id?: string;
  session_id?: string;
  target: TurnTarget;
}

export type StringList = Array<string>;

export interface TaskDescriptor {
  activity_id?: string;
  agent_handle?: string;
  current_turn_id?: string;
  handle: string;
  kind: TaskKind;
  parent_tool?: TaskParentTool;
  participant_id?: string;
  running: boolean;
  session_id: string;
  state: TaskState;
  supports_cancel?: boolean;
  supports_input?: boolean;
  task_id: string;
  title?: string;
  updated_at?: string;
}

export interface TaskDirectorySnapshot {
  revision: Uint64Decimal;
  tasks?: Array<TaskDescriptor>;
}

export interface TaskEventBatch {
  activity_id?: string;
  boundary_cursor?: string;
  events?: Array<Envelope>;
  resume_mode: TaskResumeMode;
  transient_gap?: boolean;
}

export type TaskKind = "command" | "subagent";

export interface TaskList {
  tasks?: Array<TaskDescriptor>;
}

export interface TaskParentTool {
  tool_call_id?: string;
  tool_name?: string;
}

export type TaskResumeMode = "exact" | "current_state";

export type TaskState = "prepared" | "running" | "waiting_input" | "completed" | "failed" | "cancelled" | "interrupted" | "terminated" | "waiting_approval" | "unknown_outcome";

export interface TerminalExitStatus {
  exit_code?: number;
  signal?: string;
}

export interface TerminalOutput {
  exit_status?: TerminalExitStatus;
  output: string;
  truncated: boolean;
}

export interface TerminalRequest {
  session_id: string;
  terminal_id: string;
}

export interface TextContent {
  text: string;
  type: "text";
}

export interface ToolCallContent {
  content?: JSONValue;
  newText?: string;
  oldText?: string;
  path?: string;
  terminalId?: string;
  type: string;
}

export interface ToolCallLocation {
  line?: number;
  path: string;
}

export interface TransientFeedPosition {
  anchor: DurableFeedPosition;
  generation: string;
  sequence: PositiveUint64Decimal;
}

export interface TurnTarget {
  handle_id: string;
  run_id: string;
  turn_id: string;
}

export type Uint64Decimal = string;

export interface UpdateMarketplaceRequest {
  expected_controller_epoch?: string;
  expected_revision?: Uint64Decimal;
  name: string;
  operation_id?: string;
  session_id?: string;
}

export interface UsageCost {
  _meta?: ACPMetadata;
  amount?: number;
  cache_read?: number;
  cache_write?: number;
  currency?: string;
  input?: number;
  output?: number;
  total?: number;
}

export interface UsageMetadata {
  cached_input_tokens?: Uint64Decimal;
  completion_tokens?: Uint64Decimal;
  context_window_tokens?: Uint64Decimal;
  prompt_tokens?: Uint64Decimal;
  reasoning_tokens?: Uint64Decimal;
  total_tokens?: Uint64Decimal;
  [key: string]: JSONValue;
}

export interface UsageSnapshot {
  cached_input_tokens?: number;
  completion_tokens?: number;
  prompt_tokens?: number;
  reasoning_tokens?: number;
  total_tokens?: number;
}

export interface UseModelRequest {
  expected_controller_epoch?: string;
  expected_revision?: Uint64Decimal;
  model: string;
  operation_id?: string;
  reasoning_effort?: string;
  session_id?: string;
}

export interface WriteBase {
  expected_controller_epoch?: string;
  expected_revision?: Uint64Decimal;
  operation_id?: string;
  session_id?: string;
}
