// Code generated by caelis-client-protocol-gen/v2.5.0 from api/control/v1/openapi.json; DO NOT EDIT.
export const generatorVersion = 'caelis-client-protocol-gen/v2.5.0' as const;
export const operationIds = ["attachParticipant", "cancelParticipant", "cancelSessionTurn", "closeSession", "createSession", "detachParticipant", "getSessionEvents", "getSessionState", "getTaskEvents", "handoffController", "listSessionTasks", "listSessions", "promptParticipant", "promptSession", "resolveApproval", "steerSession", "streamSessionEvents", "streamTaskEvents"] as const;
export type OperationId = typeof operationIds[number];

export interface ACPAvailableCommandsUpdate {
  availableCommands: Array<AvailableCommand>;
  sessionUpdate: "available_commands_update";
}

export interface ACPCompactUpdate {
  _meta?: ACPMetadata;
  sessionUpdate: "compact";
}

export interface ACPConfigOptionUpdate {
  configOptions: Array<JSONObject>;
  sessionUpdate: "config_option_update";
}

export interface ACPContentChunk {
  _meta?: ACPMetadata;
  content: ContentBlock;
  messageId?: string;
  sessionUpdate: "user_message_chunk" | "agent_message_chunk" | "agent_thought_chunk" | "compact";
}

export interface ACPCurrentModeUpdate {
  currentModeId: string;
  sessionUpdate: "current_mode_update";
}

export interface ACPMetadata {
  caelis?: CaelisMetadata;
  compact?: CompactMetadata;
  from?: HandoffBindingMetadata;
  to?: HandoffBindingMetadata;
  [key: string]: JSONValue;
}

export interface ACPPlanUpdate {
  entries: Array<PlanEntry>;
  sessionUpdate: "plan";
}

export interface ACPRawUpdate {
  sessionUpdate: string;
  [key: string]: JSONValue;
}

export interface ACPSessionInfoUpdate {
  sessionUpdate: "session_info_update";
  title?: string;
  updatedAt?: string;
}

export interface ACPToolCall {
  _meta?: ACPMetadata;
  content?: Array<ToolCallContent>;
  kind?: string;
  locations?: Array<ToolCallLocation>;
  rawInput?: JSONValue;
  rawOutput?: JSONValue;
  sessionUpdate: "tool_call";
  status?: string;
  title: string;
  toolCallId: string;
}

export interface ACPToolCallUpdate {
  _meta?: ACPMetadata;
  content?: Array<ToolCallContent>;
  kind?: string;
  locations?: Array<ToolCallLocation>;
  rawInput?: JSONValue;
  rawOutput?: JSONValue;
  sessionUpdate: "tool_call_update";
  status?: string;
  title?: string;
  toolCallId: string;
}

export type ACPUpdate = ACPContentChunk | ACPToolCall | ACPToolCallUpdate | ACPPlanUpdate | ACPUsageUpdate | ACPCurrentModeUpdate | ACPConfigOptionUpdate | ACPSessionInfoUpdate | ACPAvailableCommandsUpdate | ACPRawUpdate;

export interface ACPUsageUpdate {
  _meta?: ACPMetadata;
  cost?: UsageCost;
  sessionUpdate: "usage_update";
  size: Uint64Decimal;
  used: Uint64Decimal;
}

export interface ActiveApproval {
  parent_tool?: ParentToolRelation;
  participant_id?: string;
  permission: JSONObject;
  request_id: string;
  scope?: "main" | "participant" | "subagent";
  scope_id?: string;
}

export interface ApprovalReview {
  authorization?: string;
  raw_input?: JSONObject;
  risk?: string;
  status?: string;
  text?: string;
  tool_call_id?: string;
  tool_name?: string;
}

export interface ApprovalReviewEnvelope {
  _meta?: ACPMetadata;
  actor?: string;
  approval_review: ApprovalReview;
  cursor: string;
  delivery: Delivery;
  event_id?: string;
  final?: boolean;
  handle_id?: string;
  kind: "caelis/approval_review";
  occurred_at?: string;
  parent_tool?: ParentToolRelation;
  participant_id?: string;
  position: FeedPosition;
  projection_id?: string;
  run_id?: string;
  scope?: "main" | "participant" | "subagent";
  scope_id?: string;
  session_id?: string;
  turn_id?: string;
}

export interface ApprovalState {
  active?: ActiveApproval;
  queued_count?: number;
}

export interface AttachParticipantRequest {
  effort: string;
  expected_controller_epoch?: string;
  expected_revision?: Uint64Decimal;
  label?: string;
  operation_id?: string;
  profile_id: string;
  role?: ParticipantRole;
  session_id?: string;
  source?: string;
}

export interface AudioContent {
  data: string;
  mimeType: string;
  type: "audio";
}

export interface AvailableCommand {
  description?: string;
  input?: JSONObject;
  name: string;
}

export interface CaelisMetadata {
  runtime?: CaelisRuntimeMetadata;
  sdk?: SDKMetadata;
  usage?: UsageMetadata;
  [key: string]: JSONValue;
}

export interface CaelisRuntimeMetadata {
  stream?: RuntimeStreamMetadata;
  task?: RuntimeTaskMetadata;
  [key: string]: JSONValue;
}

export interface CancelParticipantRequest {
  expected_controller_epoch?: string;
  expected_revision?: Uint64Decimal;
  operation_id?: string;
  participant_id: string;
  reason?: string;
  session_id?: string;
  target: TurnTarget;
}

export interface CancelRequest {
  expected_controller_epoch?: string;
  expected_revision?: Uint64Decimal;
  operation_id?: string;
  reason?: string;
  session_id?: string;
  target: TurnTarget;
}

export interface ClientCapabilities {
  caelis_terminal_stream: true;
  client_managed_terminal: false;
  goal_bootstrap_supported: false;
  manage_loop_bootstrap_supported: false;
}

export interface CloseSessionRequest {
  expected_controller_epoch?: string;
  expected_revision?: Uint64Decimal;
  operation_id?: string;
  session_id?: string;
}

export interface CommandResult {
  detail?: string;
  operation_id: string;
  outcome: Outcome;
  revision?: Uint64Decimal;
  session_id?: string;
  target?: CommandTarget;
}

export interface CommandTarget {
  handle_id?: string;
  run_id?: string;
  turn_id?: string;
}

export interface CompactMetadata {
  context_window_tokens?: Uint64Decimal;
  contract_version?: Uint64Decimal;
  revision?: Uint64Decimal;
  source_event_count?: Uint64Decimal;
  summarized_through_seq?: Uint64Decimal;
  total_tokens?: Uint64Decimal;
  [key: string]: JSONValue;
}

export type ContentBlock = TextContent | ImageContent | AudioContent | ResourceContent;

export interface ControllerBinding {
  agent_name?: string;
  attached_at?: string;
  context_sync_seq?: Uint64Decimal;
  controller_id?: string;
  epoch_id?: string;
  kind?: ControllerKind;
  label?: string;
  remote_session_id?: string;
  source?: string;
}

export type ControllerKind = "kernel" | "acp";

export interface CreateSessionRequest {
  cwd?: string;
  expected_controller_epoch?: string;
  expected_revision?: Uint64Decimal;
  metadata?: JSONObject;
  operation_id?: string;
  preferred_session_id?: string;
  session_id?: string;
  title?: string;
  workspace_key?: string;
}

export interface Delivery {
  mode: DeliveryMode;
}

export type DeliveryMode = "canonical" | "mirror" | "transient";

export interface DetachParticipantRequest {
  expected_controller_epoch?: string;
  expected_revision?: Uint64Decimal;
  operation_id?: string;
  participant_id: string;
  session_id?: string;
  source?: string;
}

export interface DurableFeedPosition {
  projection_index: number;
  seq: Uint64Decimal;
}

export type Envelope = SessionUpdateEnvelope | RequestPermissionEnvelope | NoticeEnvelope | ParticipantEnvelope | LifecycleEnvelope | ApprovalReviewEnvelope | ErrorEnvelope;

export interface EnvelopeBase {
  _meta?: ACPMetadata;
  actor?: string;
  cursor: string;
  delivery: Delivery;
  event_id?: string;
  final?: boolean;
  handle_id?: string;
  kind: EnvelopeKind;
  occurred_at?: string;
  parent_tool?: ParentToolRelation;
  participant_id?: string;
  position: FeedPosition;
  projection_id?: string;
  run_id?: string;
  scope?: "main" | "participant" | "subagent";
  scope_id?: string;
  session_id?: string;
  turn_id?: string;
}

export type EnvelopeKind = "session/update" | "session/request_permission" | "caelis/notice" | "caelis/participant" | "caelis/lifecycle" | "caelis/approval_review" | "caelis/error";

export interface ErrorEnvelope {
  _meta?: ACPMetadata;
  actor?: string;
  cursor: string;
  delivery: Delivery;
  error: string;
  event_id?: string;
  final?: boolean;
  handle_id?: string;
  kind: "caelis/error";
  occurred_at?: string;
  parent_tool?: ParentToolRelation;
  participant_id?: string;
  position: FeedPosition;
  projection_id?: string;
  run_id?: string;
  scope?: "main" | "participant" | "subagent";
  scope_id?: string;
  session_id?: string;
  turn_id?: string;
}

export interface ErrorResponse {
  error: string;
}

export interface EventBatch {
  boundary_cursor?: string;
  events?: Array<Envelope>;
  resume_mode: ResumeMode;
  transient_gap?: boolean;
}

export type FeedPosition = { durable: DurableFeedPosition } | { transient: TransientFeedPosition };

export interface HandoffBindingMetadata {
  context_sync_seq?: Uint64Decimal;
  [key: string]: JSONValue;
}

export interface HandoffRequest {
  agent?: string;
  expected_controller_epoch?: string;
  expected_revision?: Uint64Decimal;
  kind: ControllerKind;
  operation_id?: string;
  reason?: string;
  session_id?: string;
  source?: string;
}

export interface ImageContent {
  data: string;
  mimeType: string;
  type: "image";
}

export type JSONObject = Record<string, JSONValue>;

export type JSONValue = unknown;

export interface LifecycleEnvelope {
  _meta?: ACPMetadata;
  actor?: string;
  cursor: string;
  delivery: Delivery;
  event_id?: string;
  final?: boolean;
  handle_id?: string;
  kind: "caelis/lifecycle";
  lifecycle: LifecycleEvent;
  occurred_at?: string;
  parent_tool?: ParentToolRelation;
  participant_id?: string;
  position: FeedPosition;
  projection_id?: string;
  run_id?: string;
  scope?: "main" | "participant" | "subagent";
  scope_id?: string;
  session_id?: string;
  turn_id?: string;
}

export interface LifecycleEvent {
  reason?: string;
  state: string;
  stopReason?: string;
}

export interface NoticeEnvelope {
  _meta?: ACPMetadata;
  actor?: string;
  cursor: string;
  delivery: Delivery;
  event_id?: string;
  final?: boolean;
  handle_id?: string;
  kind: "caelis/notice";
  notice: string;
  occurred_at?: string;
  parent_tool?: ParentToolRelation;
  participant_id?: string;
  position: FeedPosition;
  projection_id?: string;
  run_id?: string;
  scope?: "main" | "participant" | "subagent";
  scope_id?: string;
  session_id?: string;
  turn_id?: string;
}

export type Outcome = "accepted" | "committed" | "conflicted" | "rejected" | "unknown";

export interface ParentToolRelation {
  tool_call_id?: string;
  tool_name?: string;
}

export interface ParticipantBinding {
  agent_name?: string;
  attached_at?: string;
  attachment_generation?: string;
  context_sync_seq?: Uint64Decimal;
  controller_ref?: string;
  delegation_id?: string;
  id?: string;
  kind?: ParticipantKind;
  label?: string;
  parent_turn_id?: string;
  role?: ParticipantRole;
  session_id?: string;
  source?: string;
}

export interface ParticipantEnvelope {
  _meta?: ACPMetadata;
  actor?: string;
  cursor: string;
  delivery: Delivery;
  event_id?: string;
  final?: boolean;
  handle_id?: string;
  kind: "caelis/participant";
  occurred_at?: string;
  parent_tool?: ParentToolRelation;
  participant: ParticipantEvent;
  participant_id?: string;
  position: FeedPosition;
  projection_id?: string;
  run_id?: string;
  scope?: "main" | "participant" | "subagent";
  scope_id?: string;
  session_id?: string;
  turn_id?: string;
}

export interface ParticipantEvent {
  state: string;
}

export type ParticipantKind = "acp" | "subagent";

export type ParticipantRole = "sidecar" | "delegated" | "observer";

export interface PermissionOption {
  kind: string;
  name: string;
  optionId: string;
}

export interface PlanEntry {
  content: string;
  priority: string;
  status: string;
}

export type PositiveUint64Decimal = string;

export interface PromptParticipantRequest {
  display_input?: string;
  expected_controller_epoch?: string;
  expected_revision?: Uint64Decimal;
  input: string;
  operation_id?: string;
  participant_id: string;
  session_id?: string;
}

export interface PromptRequest {
  display_input?: string;
  expected_controller_epoch?: string;
  expected_revision?: Uint64Decimal;
  input: string;
  operation_id?: string;
  session_id?: string;
}

export interface RequestPermission {
  _meta?: ACPMetadata;
  options: Array<PermissionOption>;
  sessionId: string;
  toolCall: ACPToolCallUpdate;
}

export interface RequestPermissionEnvelope {
  _meta?: ACPMetadata;
  actor?: string;
  approval_request_id: string;
  cursor: string;
  delivery: Delivery;
  event_id?: string;
  final?: boolean;
  handle_id?: string;
  kind: "session/request_permission";
  occurred_at?: string;
  parent_tool?: ParentToolRelation;
  participant_id?: string;
  permission: RequestPermission;
  position: FeedPosition;
  projection_id?: string;
  run_id?: string;
  scope?: "main" | "participant" | "subagent";
  scope_id?: string;
  session_id?: string;
  turn_id?: string;
}

export interface ResolveApprovalRequest {
  approval_request_id: string;
  approved: boolean;
  expected_controller_epoch?: string;
  expected_revision?: Uint64Decimal;
  operation_id?: string;
  option_id?: string;
  outcome: string;
  reason?: string;
  review_text?: string;
  session_id?: string;
  target: TurnTarget;
}

export interface ResourceContent {
  mimeType?: string;
  name?: string;
  type: "resource";
  uri: string;
}

export interface ResumeBoundary {
  boundary_cursor?: string;
  resume_mode: ResumeMode;
  transient_gap?: boolean;
}

export type ResumeMode = "exact" | "durable_fallback";

export interface RunState {
  active?: boolean;
  handle_id?: string;
  kind?: string;
  run_id?: string;
  started_at?: string;
  status?: string;
  turn_id?: string;
  waiting_approval?: boolean;
}

export interface RuntimeStreamMetadata {
  truncated_before?: Uint64Decimal;
  [key: string]: JSONValue;
}

export interface RuntimeTaskMetadata {
  event_cursor?: Uint64Decimal;
  output_cursor?: Uint64Decimal;
  turn_seq?: Uint64Decimal;
  [key: string]: JSONValue;
}

export interface SDKMetadata {
  context_window_tokens?: Uint64Decimal;
  usage?: SDKUsageMetadata;
  [key: string]: JSONValue;
}

export interface SDKUsageMetadata {
  cached_input_tokens?: Uint64Decimal;
  completion_tokens?: Uint64Decimal;
  context_window_tokens?: Uint64Decimal;
  cost_micros?: Uint64Decimal;
  prompt_tokens?: Uint64Decimal;
  reasoning_tokens?: Uint64Decimal;
  total_tokens?: Uint64Decimal;
  [key: string]: JSONValue;
}

export interface SessionList {
  next_cursor?: string;
  sessions?: Array<SessionSummary>;
}

export interface SessionRef {
  app_name?: string;
  session_id?: string;
  user_id?: string;
  workspace_key?: string;
}

export interface SessionState {
  api_version: string;
  approval: ApprovalState;
  boundary_cursor?: string;
  boundary_position?: FeedPosition;
  capabilities: ClientCapabilities;
  controller: ControllerBinding;
  cwd?: string;
  envelope_version: string;
  metadata?: JSONObject;
  participants?: Array<ParticipantBinding>;
  protocol_version: number;
  resume_mode: ResumeMode;
  revision: Uint64Decimal;
  run: RunState;
  session_id: string;
  title?: string;
  transient_gap?: boolean;
  workspace_key?: string;
}

export interface SessionSummary {
  app_name?: string;
  cwd?: string;
  metadata?: JSONObject;
  session_id?: string;
  title?: string;
  updated_at?: string;
  user_id?: string;
  workspace_key?: string;
}

export interface SessionUpdateEnvelope {
  _meta?: ACPMetadata;
  actor?: string;
  cursor: string;
  delivery: Delivery;
  event_id?: string;
  final?: boolean;
  handle_id?: string;
  kind: "session/update";
  occurred_at?: string;
  parent_tool?: ParentToolRelation;
  participant_id?: string;
  position: FeedPosition;
  projection_id?: string;
  run_id?: string;
  scope?: "main" | "participant" | "subagent";
  scope_id?: string;
  session_id?: string;
  turn_id?: string;
  update: ACPUpdate;
}

export interface SteerRequest {
  display_input?: string;
  expected_controller_epoch?: string;
  expected_revision?: Uint64Decimal;
  input: string;
  operation_id?: string;
  session_id?: string;
  target: TurnTarget;
}

export interface TaskDescriptor {
  agent_handle?: string;
  current_turn_id?: string;
  handle: string;
  kind: TaskKind;
  parent_tool?: ParentToolRelation;
  participant_id?: string;
  running: boolean;
  session_id: string;
  state: TaskState;
  supports_cancel?: boolean;
  supports_input?: boolean;
  task_id: string;
  title?: string;
  updated_at?: string;
}

export interface TaskEventBatch {
  boundary_cursor?: string;
  events?: Array<Envelope>;
  resume_mode: TaskResumeMode;
  transient_gap?: boolean;
}

export type TaskKind = "command" | "subagent";

export interface TaskList {
  tasks?: Array<TaskDescriptor>;
}

export interface TaskResumeBoundary {
  boundary_cursor?: string;
  resume_mode: TaskResumeMode;
  transient_gap?: boolean;
}

export type TaskResumeMode = "exact" | "current_state";

export type TaskState = "prepared" | "running" | "waiting_input" | "waiting_approval" | "completed" | "failed" | "cancelled" | "interrupted" | "terminated" | "unknown_outcome";

export interface TextContent {
  text: string;
  type: "text";
}

export interface ToolCallContent {
  content?: JSONValue;
  newText?: string;
  oldText?: string;
  path?: string;
  terminalId?: string;
  type: string;
}

export interface ToolCallLocation {
  line?: number;
  path: string;
}

export interface TransientFeedPosition {
  anchor: DurableFeedPosition;
  generation: string;
  sequence: PositiveUint64Decimal;
}

export interface TurnTarget {
  handle_id: string;
  run_id: string;
  turn_id: string;
}

export type Uint64Decimal = string;

export interface UsageCost {
  cache_read?: number;
  cache_write?: number;
  currency?: string;
  input?: number;
  output?: number;
  total?: number;
}

export interface UsageMetadata {
  cached_input_tokens?: Uint64Decimal;
  completion_tokens?: Uint64Decimal;
  context_window_tokens?: Uint64Decimal;
  prompt_tokens?: Uint64Decimal;
  reasoning_tokens?: Uint64Decimal;
  total_tokens?: Uint64Decimal;
  [key: string]: JSONValue;
}

export interface WriteBase {
  expected_controller_epoch?: string;
  expected_revision?: Uint64Decimal;
  operation_id?: string;
  session_id?: string;
}
