package modelcatalog

// catalogEntry maps a provider+model pattern to capabilities.
type catalogEntry struct {
	provider                  string // provider name (e.g. "deepseek", "openai")
	pattern                   string // model name prefix or exact match (e.g. "deepseek-v4-flash", "gpt-4o")
	hiddenFromRecommendations bool   // retain capability lookup without advertising the model for new configurations
	caps                      ModelCapabilities
}

// builtinCatalog is the static registry of known model capabilities.
// Add new SOTA models here as they become available.
var builtinCatalog = []catalogEntry{
	// ── xAI ───────────────────────────────────────────────────────────────
	{
		provider: "xai",
		pattern:  "grok-4.6",
		caps: ModelCapabilities{
			ContextWindowTokens:    500000,
			DefaultMaxOutputTokens: 32768,
			SupportsImages:         true,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeEffort,
			ReasoningEfforts:       []string{"low", "medium", "high", "xhigh"},
			DefaultReasoningEffort: "high",
			SupportsJSONOutput:     true,
		},
	},
	{
		provider:                  "xai",
		pattern:                   "grok-4.5",
		hiddenFromRecommendations: true,
		caps: ModelCapabilities{
			ContextWindowTokens:    500000,
			DefaultMaxOutputTokens: 32768,
			SupportsImages:         true,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeEffort,
			ReasoningEfforts:       []string{"low", "medium", "high"},
			DefaultReasoningEffort: "high",
			SupportsJSONOutput:     true,
		},
	},
	// ── DeepSeek ──────────────────────────────────────────────────────────
	{
		provider: "deepseek",
		pattern:  "deepseek-v4-flash-vision-exp",
		caps: ModelCapabilities{
			ContextWindowTokens:    1048576,
			MaxOutputTokens:        393216,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeToggle,
			ReasoningEfforts:       []string{"low", "high", "max"},
			DefaultReasoningEffort: "high",
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "deepseek",
		pattern:  "deepseek-v4-flash",
		caps: ModelCapabilities{
			ContextWindowTokens:    1048576,
			MaxOutputTokens:        393216,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeToggle,
			ReasoningEfforts:       []string{"low", "high", "max"},
			DefaultReasoningEffort: "high",
			SupportsJSONOutput:     true,
			SupportsImages:         false,
		},
	},
	{
		provider: "deepseek",
		pattern:  "deepseek-v4-pro",
		caps: ModelCapabilities{
			ContextWindowTokens:    1048576,
			MaxOutputTokens:        393216,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeToggle,
			ReasoningEfforts:       []string{"low", "high", "max"},
			DefaultReasoningEffort: "high",
			SupportsJSONOutput:     true,
			SupportsImages:         false,
		},
	},
	// ── OpenAI ────────────────────────────────────────────────────────────
	{
		provider: "openai",
		pattern:  "gpt-6-astra",
		caps: ModelCapabilities{
			ContextWindowTokens:    1050000,
			MaxOutputTokens:        128000,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeEffort,
			ReasoningEfforts:       []string{"low", "medium", "high", "xhigh", "max"},
			DefaultReasoningEffort: "medium",
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "openai",
		pattern:  "gpt-5.6-sol",
		caps: ModelCapabilities{
			ContextWindowTokens:    1050000,
			MaxOutputTokens:        128000,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeEffort,
			ReasoningEfforts:       []string{"none", "low", "medium", "high", "xhigh", "max"},
			DefaultReasoningEffort: "medium",
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "openai",
		pattern:  "gpt-5.6-terra",
		caps: ModelCapabilities{
			ContextWindowTokens:    1050000,
			MaxOutputTokens:        128000,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeEffort,
			ReasoningEfforts:       []string{"none", "low", "medium", "high", "xhigh", "max"},
			DefaultReasoningEffort: "medium",
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "openai",
		pattern:  "gpt-5.6-luna",
		caps: ModelCapabilities{
			ContextWindowTokens:    1050000,
			MaxOutputTokens:        128000,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeEffort,
			ReasoningEfforts:       []string{"none", "low", "medium", "high", "xhigh", "max"},
			DefaultReasoningEffort: "medium",
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider:                  "openai",
		pattern:                   "gpt-5.5",
		hiddenFromRecommendations: true,
		caps: ModelCapabilities{
			ContextWindowTokens:    1050000,
			MaxOutputTokens:        128000,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeEffort,
			ReasoningEfforts:       []string{"none", "low", "medium", "high", "xhigh"},
			DefaultReasoningEffort: "medium",
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider:                  "openai",
		pattern:                   "gpt-5.5-pro",
		hiddenFromRecommendations: true,
		caps: ModelCapabilities{
			ContextWindowTokens:    1050000,
			MaxOutputTokens:        128000,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeEffort,
			ReasoningEfforts:       []string{"none", "low", "medium", "high", "xhigh"},
			DefaultReasoningEffort: "medium",
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider:                  "openai",
		pattern:                   "gpt-5.5-instant",
		hiddenFromRecommendations: true,
		caps: ModelCapabilities{
			ContextWindowTokens:    400000,
			MaxOutputTokens:        128000,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeEffort,
			ReasoningEfforts:       []string{"none", "low", "medium", "high", "xhigh"},
			DefaultReasoningEffort: "medium",
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider:                  "openai",
		pattern:                   "gpt-5.4",
		hiddenFromRecommendations: true,
		caps: ModelCapabilities{
			ContextWindowTokens:    1050000,
			MaxOutputTokens:        128000,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeEffort,
			ReasoningEfforts:       []string{"none", "low", "medium", "high", "xhigh"},
			DefaultReasoningEffort: "medium",
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider:                  "openai",
		pattern:                   "gpt-5.4-pro",
		hiddenFromRecommendations: true,
		caps: ModelCapabilities{
			ContextWindowTokens:    1050000,
			MaxOutputTokens:        128000,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeEffort,
			ReasoningEfforts:       []string{"none", "low", "medium", "high", "xhigh"},
			DefaultReasoningEffort: "medium",
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider:                  "openai",
		pattern:                   "gpt-5.4-mini",
		hiddenFromRecommendations: true,
		caps: ModelCapabilities{
			ContextWindowTokens:    400000,
			MaxOutputTokens:        128000,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeEffort,
			ReasoningEfforts:       []string{"none", "low", "medium", "high", "xhigh"},
			DefaultReasoningEffort: "medium",
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider:                  "openai",
		pattern:                   "gpt-5.4-nano",
		hiddenFromRecommendations: true,
		caps: ModelCapabilities{
			ContextWindowTokens:    400000,
			MaxOutputTokens:        128000,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeEffort,
			ReasoningEfforts:       []string{"none", "low", "medium", "high", "xhigh"},
			DefaultReasoningEffort: "medium",
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider:                  "openai",
		pattern:                   "gpt-4o",
		hiddenFromRecommendations: true,
		caps: ModelCapabilities{
			ContextWindowTokens:    128000,
			MaxOutputTokens:        16384,
			DefaultMaxOutputTokens: 4096,
			SupportsToolCalls:      true,
			SupportsReasoning:      false,
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider:                  "openai",
		pattern:                   "gpt-4o-mini",
		hiddenFromRecommendations: true,
		caps: ModelCapabilities{
			ContextWindowTokens:    128000,
			MaxOutputTokens:        16384,
			DefaultMaxOutputTokens: 4096,
			SupportsToolCalls:      true,
			SupportsReasoning:      false,
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider:                  "openai",
		pattern:                   "o1",
		hiddenFromRecommendations: true,
		caps: ModelCapabilities{
			ContextWindowTokens:    200000,
			MaxOutputTokens:        100000,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningEfforts:       []string{"low", "medium", "high"},
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider:                  "openai",
		pattern:                   "o1-mini",
		hiddenFromRecommendations: true,
		caps: ModelCapabilities{
			ContextWindowTokens:    128000,
			MaxOutputTokens:        65536,
			DefaultMaxOutputTokens: 16384,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningEfforts:       []string{"low", "medium", "high"},
			SupportsJSONOutput:     true,
			SupportsImages:         false,
		},
	},
	{
		provider:                  "openai",
		pattern:                   "o3",
		hiddenFromRecommendations: true,
		caps: ModelCapabilities{
			ContextWindowTokens:    200000,
			MaxOutputTokens:        100000,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningEfforts:       []string{"low", "medium", "high", "xhigh"},
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider:                  "openai",
		pattern:                   "o3-mini",
		hiddenFromRecommendations: true,
		caps: ModelCapabilities{
			ContextWindowTokens:    200000,
			MaxOutputTokens:        100000,
			DefaultMaxOutputTokens: 16384,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningEfforts:       []string{"low", "medium", "high", "xhigh"},
			SupportsJSONOutput:     true,
			SupportsImages:         false,
		},
	},
	{
		provider:                  "openai",
		pattern:                   "o4-mini",
		hiddenFromRecommendations: true,
		caps: ModelCapabilities{
			ContextWindowTokens:    200000,
			MaxOutputTokens:        100000,
			DefaultMaxOutputTokens: 16384,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningEfforts:       []string{"low", "medium", "high", "xhigh"},
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider:                  "openai",
		pattern:                   "gpt-4.1",
		hiddenFromRecommendations: true,
		caps: ModelCapabilities{
			ContextWindowTokens:    1047576,
			MaxOutputTokens:        32768,
			DefaultMaxOutputTokens: 16384,
			SupportsToolCalls:      true,
			SupportsReasoning:      false,
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider:                  "openai",
		pattern:                   "gpt-4.1-mini",
		hiddenFromRecommendations: true,
		caps: ModelCapabilities{
			ContextWindowTokens:    1047576,
			MaxOutputTokens:        32768,
			DefaultMaxOutputTokens: 16384,
			SupportsToolCalls:      true,
			SupportsReasoning:      false,
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider:                  "openai",
		pattern:                   "gpt-4.1-nano",
		hiddenFromRecommendations: true,
		caps: ModelCapabilities{
			ContextWindowTokens:    1047576,
			MaxOutputTokens:        32768,
			DefaultMaxOutputTokens: 16384,
			SupportsToolCalls:      true,
			SupportsReasoning:      false,
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	// ── Anthropic ─────────────────────────────────────────────────────────
	{
		provider: "anthropic",
		pattern:  "claude-fable-5-1",
		caps: ModelCapabilities{
			ContextWindowTokens:    1000000,
			MaxOutputTokens:        128000,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeEffort,
			ReasoningEfforts:       []string{"low", "medium", "high", "xhigh", "max"},
			DefaultReasoningEffort: "high",
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "anthropic",
		pattern:  "claude-mythos-5-1",
		caps: ModelCapabilities{
			ContextWindowTokens:    1000000,
			MaxOutputTokens:        128000,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeEffort,
			ReasoningEfforts:       []string{"low", "medium", "high", "xhigh", "max"},
			DefaultReasoningEffort: "high",
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "anthropic",
		pattern:  "claude-opus-5",
		caps: ModelCapabilities{
			ContextWindowTokens:    1000000,
			MaxOutputTokens:        128000,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeEffort,
			ReasoningEfforts:       []string{"low", "medium", "high", "xhigh", "max"},
			DefaultReasoningEffort: "high",
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "anthropic",
		pattern:  "claude-sonnet-5",
		caps: ModelCapabilities{
			ContextWindowTokens:    1000000,
			MaxOutputTokens:        128000,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeEffort,
			ReasoningEfforts:       []string{"low", "medium", "high", "xhigh", "max"},
			DefaultReasoningEffort: "high",
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider:                  "anthropic",
		pattern:                   "claude-fable-5",
		hiddenFromRecommendations: true,
		caps: ModelCapabilities{
			ContextWindowTokens:    1000000,
			MaxOutputTokens:        128000,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeEffort,
			ReasoningEfforts:       []string{"low", "medium", "high", "xhigh", "max"},
			DefaultReasoningEffort: "high",
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider:                  "anthropic",
		pattern:                   "claude-mythos-5",
		hiddenFromRecommendations: true,
		caps: ModelCapabilities{
			ContextWindowTokens:    1000000,
			MaxOutputTokens:        128000,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeEffort,
			ReasoningEfforts:       []string{"low", "medium", "high", "xhigh", "max"},
			DefaultReasoningEffort: "high",
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider:                  "anthropic",
		pattern:                   "claude-opus-4-8",
		hiddenFromRecommendations: true,
		caps: ModelCapabilities{
			ContextWindowTokens:    1000000,
			MaxOutputTokens:        128000,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeEffort,
			ReasoningEfforts:       []string{"low", "medium", "high", "xhigh", "max"},
			DefaultReasoningEffort: "high",
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider:                  "anthropic",
		pattern:                   "claude-sonnet-4-6",
		hiddenFromRecommendations: true,
		caps: ModelCapabilities{
			ContextWindowTokens:    1000000,
			MaxOutputTokens:        128000,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeEffort,
			ReasoningEfforts:       []string{"low", "medium", "high", "max"},
			DefaultReasoningEffort: "high",
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "anthropic",
		pattern:  "claude-haiku-4-5",
		caps: ModelCapabilities{
			ContextWindowTokens:    200000,
			MaxOutputTokens:        64000,
			DefaultMaxOutputTokens: 16384,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeToggle,
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider:                  "anthropic",
		pattern:                   "claude-sonnet-4",
		hiddenFromRecommendations: true,
		caps: ModelCapabilities{
			ContextWindowTokens:    200000,
			MaxOutputTokens:        64000,
			DefaultMaxOutputTokens: 16384,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningEfforts:       []string{"low", "medium", "high"},
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider:                  "anthropic",
		pattern:                   "claude-3-7-sonnet",
		hiddenFromRecommendations: true,
		caps: ModelCapabilities{
			ContextWindowTokens:    200000,
			MaxOutputTokens:        64000,
			DefaultMaxOutputTokens: 16384,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningEfforts:       []string{"low", "medium", "high"},
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider:                  "anthropic",
		pattern:                   "claude-3-5-sonnet",
		hiddenFromRecommendations: true,
		caps: ModelCapabilities{
			ContextWindowTokens:    200000,
			MaxOutputTokens:        8192,
			DefaultMaxOutputTokens: 4096,
			SupportsToolCalls:      true,
			SupportsReasoning:      false,
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider:                  "anthropic",
		pattern:                   "claude-3-5-haiku",
		hiddenFromRecommendations: true,
		caps: ModelCapabilities{
			ContextWindowTokens:    200000,
			MaxOutputTokens:        8192,
			DefaultMaxOutputTokens: 4096,
			SupportsToolCalls:      true,
			SupportsReasoning:      false,
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider:                  "anthropic",
		pattern:                   "claude-opus-4",
		hiddenFromRecommendations: true,
		caps: ModelCapabilities{
			ContextWindowTokens:    200000,
			MaxOutputTokens:        64000,
			DefaultMaxOutputTokens: 16384,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningEfforts:       []string{"low", "medium", "high"},
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	// ── MiniMax (Anthropic-compatible) ───────────────────────────────────
	{
		provider: "minimax",
		pattern:  "MiniMax-M3",
		caps: ModelCapabilities{
			ContextWindowTokens:    1000000,
			MaxOutputTokens:        524288,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeToggle,
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider:                  "minimax",
		pattern:                   "MiniMax-M2.7",
		hiddenFromRecommendations: true,
		caps: ModelCapabilities{
			ContextWindowTokens:    204800,
			MaxOutputTokens:        204800,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeFixed,
			SupportsJSONOutput:     true,
			SupportsImages:         false,
		},
	},
	{
		provider:                  "minimax",
		pattern:                   "MiniMax-M2.7-highspeed",
		hiddenFromRecommendations: true,
		caps: ModelCapabilities{
			ContextWindowTokens:    204800,
			MaxOutputTokens:        204800,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeFixed,
			SupportsJSONOutput:     true,
			SupportsImages:         false,
		},
	},
	{
		provider:                  "minimax",
		pattern:                   "MiniMax-M2.5",
		hiddenFromRecommendations: true,
		caps: ModelCapabilities{
			ContextWindowTokens:    204800,
			MaxOutputTokens:        204800,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeFixed,
			SupportsJSONOutput:     true,
			SupportsImages:         false,
		},
	},
	{
		provider:                  "minimax",
		pattern:                   "MiniMax-M2.5-highspeed",
		hiddenFromRecommendations: true,
		caps: ModelCapabilities{
			ContextWindowTokens:    204800,
			MaxOutputTokens:        204800,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeFixed,
			SupportsJSONOutput:     true,
			SupportsImages:         false,
		},
	},
	{
		provider:                  "minimax",
		pattern:                   "MiniMax-M2.1",
		hiddenFromRecommendations: true,
		caps: ModelCapabilities{
			ContextWindowTokens:    204800,
			MaxOutputTokens:        204800,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeFixed,
			SupportsJSONOutput:     true,
			SupportsImages:         false,
		},
	},
	{
		provider:                  "minimax",
		pattern:                   "MiniMax-M2.1-highspeed",
		hiddenFromRecommendations: true,
		caps: ModelCapabilities{
			ContextWindowTokens:    204800,
			MaxOutputTokens:        204800,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeFixed,
			SupportsJSONOutput:     true,
			SupportsImages:         false,
		},
	},
	{
		provider:                  "minimax",
		pattern:                   "MiniMax-M2",
		hiddenFromRecommendations: true,
		caps: ModelCapabilities{
			ContextWindowTokens:    204800,
			MaxOutputTokens:        204800,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeFixed,
			SupportsJSONOutput:     true,
			SupportsImages:         false,
		},
	},
	// ── Gemini ────────────────────────────────────────────────────────────
	{
		provider: "gemini",
		pattern:  "gemini-3.8-flash",
		caps: ModelCapabilities{
			ContextWindowTokens:    1048576,
			MaxOutputTokens:        65536,
			DefaultMaxOutputTokens: 8192,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeEffort,
			ReasoningEfforts:       []string{"low", "medium", "high"},
			DefaultReasoningEffort: "medium",
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "gemini",
		pattern:  "gemini-3.7-flash",
		caps: ModelCapabilities{
			ContextWindowTokens:    1048576,
			MaxOutputTokens:        65536,
			DefaultMaxOutputTokens: 8192,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeEffort,
			ReasoningEfforts:       []string{"low", "medium", "high"},
			DefaultReasoningEffort: "medium",
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "gemini",
		pattern:  "gemini-3.6-flash",
		caps: ModelCapabilities{
			ContextWindowTokens:    1048576,
			MaxOutputTokens:        65536,
			DefaultMaxOutputTokens: 8192,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeEffort,
			ReasoningEfforts:       []string{"minimal", "low", "medium", "high"},
			DefaultReasoningEffort: "medium",
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "gemini",
		pattern:  "gemini-3.5-flash-lite",
		caps: ModelCapabilities{
			ContextWindowTokens:    1048576,
			MaxOutputTokens:        65536,
			DefaultMaxOutputTokens: 8192,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeEffort,
			ReasoningEfforts:       []string{"minimal", "low", "medium", "high"},
			DefaultReasoningEffort: "minimal",
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider:                  "gemini",
		pattern:                   "gemini-3.5-flash",
		hiddenFromRecommendations: true,
		caps: ModelCapabilities{
			ContextWindowTokens:    1048576,
			MaxOutputTokens:        65536,
			DefaultMaxOutputTokens: 8192,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeEffort,
			ReasoningEfforts:       []string{"low", "medium", "high"},
			DefaultReasoningEffort: "medium",
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "gemini",
		pattern:  "gemini-3.1-pro-preview",
		caps: ModelCapabilities{
			ContextWindowTokens:    1048576,
			MaxOutputTokens:        65536,
			DefaultMaxOutputTokens: 8192,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeEffort,
			ReasoningEfforts:       []string{"low", "medium", "high"},
			DefaultReasoningEffort: "high",
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "gemini",
		pattern:  "gemini-3.1-pro-preview-customtools",
		caps: ModelCapabilities{
			ContextWindowTokens:    1048576,
			MaxOutputTokens:        65536,
			DefaultMaxOutputTokens: 8192,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeEffort,
			ReasoningEfforts:       []string{"low", "medium", "high"},
			DefaultReasoningEffort: "high",
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider:                  "gemini",
		pattern:                   "gemini-3-flash-preview",
		hiddenFromRecommendations: true,
		caps: ModelCapabilities{
			ContextWindowTokens:    1048576,
			MaxOutputTokens:        65536,
			DefaultMaxOutputTokens: 8192,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeEffort,
			ReasoningEfforts:       []string{"low", "medium", "high"},
			DefaultReasoningEffort: "medium",
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider:                  "gemini",
		pattern:                   "gemini-3.1-flash-lite",
		hiddenFromRecommendations: true,
		caps: ModelCapabilities{
			ContextWindowTokens:    1048576,
			MaxOutputTokens:        65536,
			DefaultMaxOutputTokens: 8192,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeEffort,
			ReasoningEfforts:       []string{"low", "medium", "high"},
			DefaultReasoningEffort: "medium",
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider:                  "gemini",
		pattern:                   "gemini-2.5-pro",
		hiddenFromRecommendations: true,
		caps: ModelCapabilities{
			ContextWindowTokens:    1048576,
			MaxOutputTokens:        65536,
			DefaultMaxOutputTokens: 8192,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningEfforts:       []string{"low", "medium", "high"},
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider:                  "gemini",
		pattern:                   "gemini-2.5-flash",
		hiddenFromRecommendations: true,
		caps: ModelCapabilities{
			ContextWindowTokens:    1048576,
			MaxOutputTokens:        65536,
			DefaultMaxOutputTokens: 8192,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningEfforts:       []string{"low", "medium", "high"},
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider:                  "gemini",
		pattern:                   "gemini-2.0-flash",
		hiddenFromRecommendations: true,
		caps: ModelCapabilities{
			ContextWindowTokens:    1048576,
			MaxOutputTokens:        8192,
			DefaultMaxOutputTokens: 8192,
			SupportsToolCalls:      true,
			SupportsReasoning:      false,
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	// ── Mimo ──────────────────────────────────────────────────────────────
	{
		provider: "xiaomi",
		pattern:  "mimo-v2.5-pro",
		caps: ModelCapabilities{
			ContextWindowTokens:    1048576,
			MaxOutputTokens:        131072,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeToggle,
			SupportsJSONOutput:     true,
			SupportsImages:         false,
		},
	},
	{
		provider: "xiaomi",
		pattern:  "mimo-v2.5",
		caps: ModelCapabilities{
			ContextWindowTokens:    1048576,
			MaxOutputTokens:        131072,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeToggle,
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	// ── Volcengine Coding Plan ────────────────────────────────────────────
	{
		provider: "volcengine",
		pattern:  "doubao-seed-evolving",
		caps: ModelCapabilities{
			ContextWindowTokens:    1048576,
			MaxOutputTokens:        262144,
			DefaultMaxOutputTokens: 8192,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeToggle,
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "volcengine",
		pattern:  "doubao-seed-2.1-turbo",
		caps: ModelCapabilities{
			ContextWindowTokens:    262144,
			MaxOutputTokens:        262144,
			DefaultMaxOutputTokens: 8192,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeToggle,
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "volcengine",
		pattern:  "deepseek-v4-flash",
		caps: ModelCapabilities{
			ContextWindowTokens:    1048576,
			MaxOutputTokens:        393216,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeToggle,
			ReasoningEfforts:       []string{"low", "high", "max"},
			DefaultReasoningEffort: "high",
			SupportsJSONOutput:     true,
		},
	},
	{
		provider: "volcengine",
		pattern:  "deepseek-v4-pro",
		caps: ModelCapabilities{
			ContextWindowTokens:    1048576,
			MaxOutputTokens:        393216,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeToggle,
			ReasoningEfforts:       []string{"low", "high", "max"},
			DefaultReasoningEffort: "high",
			SupportsJSONOutput:     true,
		},
	},
	{
		provider: "volcengine",
		pattern:  "glm-5.3",
		caps: ModelCapabilities{
			ContextWindowTokens:    1048576,
			MaxOutputTokens:        131072,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeFixed,
			SupportsJSONOutput:     true,
		},
	},
	{
		provider: "volcengine",
		pattern:  "glm-5.3-flash",
		caps: ModelCapabilities{
			ContextWindowTokens:    1048576,
			MaxOutputTokens:        131072,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeFixed,
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "volcengine",
		pattern:  "minimax-m3",
		caps: ModelCapabilities{
			ContextWindowTokens:    1048576,
			MaxOutputTokens:        131072,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeToggle,
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "volcengine",
		pattern:  "kimi-k2.7-code",
		caps: ModelCapabilities{
			ContextWindowTokens:    262144,
			MaxOutputTokens:        32768,
			DefaultMaxOutputTokens: 8192,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeToggle,
			SupportsJSONOutput:     true,
		},
	},
	{
		provider:                  "volcengine",
		pattern:                   "kimi-k3",
		hiddenFromRecommendations: true,
		caps: ModelCapabilities{
			ContextWindowTokens:    1048576,
			MaxOutputTokens:        131072,
			DefaultMaxOutputTokens: 32768,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			ReasoningMode:          ReasoningModeToggle,
			SupportsJSONOutput:     true,
		},
	},
	{
		provider:                  "volcengine",
		pattern:                   "doubao-seed-1.8",
		hiddenFromRecommendations: true,
		caps: ModelCapabilities{
			ContextWindowTokens:    256000,
			MaxOutputTokens:        64000,
			DefaultMaxOutputTokens: 8192,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider:                  "volcengine",
		pattern:                   "doubao-seed-2.0-code",
		hiddenFromRecommendations: true,
		caps: ModelCapabilities{
			ContextWindowTokens:    256000,
			MaxOutputTokens:        32000,
			DefaultMaxOutputTokens: 8192,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider:                  "volcengine",
		pattern:                   "doubao-seed-2.0-pro",
		hiddenFromRecommendations: true,
		caps: ModelCapabilities{
			ContextWindowTokens:    256000,
			MaxOutputTokens:        64000,
			DefaultMaxOutputTokens: 8192,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider: "volcengine",
		pattern:  "doubao-seed-2.0-lite",
		caps: ModelCapabilities{
			ContextWindowTokens:    256000,
			MaxOutputTokens:        128000,
			DefaultMaxOutputTokens: 8192,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider:                  "volcengine",
		pattern:                   "doubao-seed-2.0-mini",
		hiddenFromRecommendations: true,
		caps: ModelCapabilities{
			ContextWindowTokens:    256000,
			MaxOutputTokens:        128000,
			DefaultMaxOutputTokens: 8192,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider:                  "volcengine",
		pattern:                   "doubao-seed-code",
		hiddenFromRecommendations: true,
		caps: ModelCapabilities{
			ContextWindowTokens:    256000,
			MaxOutputTokens:        64000,
			DefaultMaxOutputTokens: 8192,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			SupportsJSONOutput:     true,
			SupportsImages:         true,
		},
	},
	{
		provider:                  "volcengine",
		pattern:                   "minimax-m2.5",
		hiddenFromRecommendations: true,
		caps: ModelCapabilities{
			ContextWindowTokens:    128000,
			MaxOutputTokens:        32768,
			DefaultMaxOutputTokens: 8192,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			SupportsJSONOutput:     true,
		},
	},
	{
		provider:                  "volcengine",
		pattern:                   "glm-4.7",
		hiddenFromRecommendations: true,
		caps: ModelCapabilities{
			ContextWindowTokens:    200000,
			MaxOutputTokens:        131072,
			DefaultMaxOutputTokens: 8192,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			SupportsJSONOutput:     true,
		},
	},
	{
		provider:                  "volcengine",
		pattern:                   "deepseek-v3.2",
		hiddenFromRecommendations: true,
		caps: ModelCapabilities{
			ContextWindowTokens:    128000,
			MaxOutputTokens:        32768,
			DefaultMaxOutputTokens: 8192,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			SupportsJSONOutput:     true,
		},
	},
	{
		provider:                  "volcengine",
		pattern:                   "kimi-k2.5",
		hiddenFromRecommendations: true,
		caps: ModelCapabilities{
			ContextWindowTokens:    128000,
			MaxOutputTokens:        32768,
			DefaultMaxOutputTokens: 8192,
			SupportsToolCalls:      true,
			SupportsReasoning:      true,
			SupportsJSONOutput:     true,
		},
	},
}

func init() {
	builtinCatalog = append(builtinCatalog, ollamaCloudCatalogEntries()...)
}
