package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/ast"
	"go/doc"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"strings"
)

const (
	defaultAllowlist = "agent-sdk/supported-packages.txt"
	defaultSnapshot  = "agent-sdk/api.txt"
)

type listedPackage struct {
	ImportPath string
	Dir        string
	GoFiles    []string
	CgoFiles   []string
}

func main() {
	write := flag.Bool("write", false, "write the current supported API snapshot")
	check := flag.Bool("check", false, "compare the current supported API to the committed snapshot")
	flag.Parse()
	if *write == *check {
		fatalf("exactly one of -write or -check is required")
	}
	packages, err := readAllowlist(defaultAllowlist)
	if err != nil {
		fatalf("read allowlist: %v", err)
	}
	current, err := buildSnapshot(packages)
	if err != nil {
		fatalf("build snapshot: %v", err)
	}
	if *write {
		if err := os.WriteFile(defaultSnapshot, current, 0o644); err != nil {
			fatalf("write snapshot: %v", err)
		}
		return
	}
	want, err := os.ReadFile(defaultSnapshot)
	if err != nil {
		fatalf("read committed snapshot: %v", err)
	}
	if bytes.Equal(current, want) {
		return
	}
	tmp, err := os.CreateTemp("", "caelis-sdk-api-*.txt")
	if err != nil {
		fatalf("create current snapshot: %v", err)
	}
	name := tmp.Name()
	defer os.Remove(name)
	if _, err := tmp.Write(current); err != nil {
		fatalf("write current snapshot: %v", err)
	}
	if err := tmp.Close(); err != nil {
		fatalf("close current snapshot: %v", err)
	}
	diff := exec.Command("git", "diff", "--no-index", "--", defaultSnapshot, name)
	diff.Stdout = os.Stderr
	diff.Stderr = os.Stderr
	_ = diff.Run()
	fatalf("supported Agent SDK API changed; review compatibility and run `go run ./scripts/sdk_api_snapshot -write` for an intentional change")
}

func readAllowlist(path string) ([]string, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var out []string
	seen := map[string]struct{}{}
	for lineNumber, line := range strings.Split(string(raw), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if !strings.HasPrefix(line, "github.com/caelis-labs/caelis/agent-sdk") {
			return nil, fmt.Errorf("line %d: unsupported import path %q", lineNumber+1, line)
		}
		if _, ok := seen[line]; ok {
			return nil, fmt.Errorf("line %d: duplicate import path %q", lineNumber+1, line)
		}
		seen[line] = struct{}{}
		out = append(out, line)
	}
	if len(out) == 0 {
		return nil, fmt.Errorf("allowlist is empty")
	}
	if !slices.IsSorted(out) {
		return nil, fmt.Errorf("allowlist must be sorted")
	}
	return out, nil
}

func buildSnapshot(importPaths []string) ([]byte, error) {
	var out strings.Builder
	out.WriteString("# Code generated by scripts/sdk_api_snapshot.go; DO NOT EDIT.\n")
	out.WriteString("# Supported Agent SDK source declarations for pre-v1 compatibility review.\n")
	for _, importPath := range importPaths {
		pkg, err := loadPackage(importPath)
		if err != nil {
			return nil, err
		}
		declarations, err := packageDeclarations(pkg)
		if err != nil {
			return nil, err
		}
		out.WriteString("\npackage ")
		out.WriteString(importPath)
		out.WriteString("\n")
		for _, declaration := range declarations {
			for _, line := range strings.Split(declaration, "\n") {
				out.WriteString("  ")
				out.WriteString(strings.ReplaceAll(line, "\t", "    "))
				out.WriteByte('\n')
			}
		}
	}
	return []byte(out.String()), nil
}

func loadPackage(importPath string) (listedPackage, error) {
	cmd := exec.Command("go", "list", "-json", importPath)
	raw, err := cmd.Output()
	if err != nil {
		return listedPackage{}, fmt.Errorf("go list %s: %w", importPath, err)
	}
	var pkg listedPackage
	if err := json.Unmarshal(raw, &pkg); err != nil {
		return listedPackage{}, fmt.Errorf("decode go list %s: %w", importPath, err)
	}
	if pkg.ImportPath != importPath || pkg.Dir == "" {
		return listedPackage{}, fmt.Errorf("go list returned invalid package for %s", importPath)
	}
	return pkg, nil
}

func packageDeclarations(pkg listedPackage) ([]string, error) {
	fset := token.NewFileSet()
	files := make([]*ast.File, 0, len(pkg.GoFiles)+len(pkg.CgoFiles))
	for _, name := range append(slices.Clone(pkg.GoFiles), pkg.CgoFiles...) {
		path := filepath.Join(pkg.Dir, name)
		file, err := parser.ParseFile(fset, path, nil, 0)
		if err != nil {
			return nil, fmt.Errorf("parse %s: %w", path, err)
		}
		files = append(files, file)
	}
	documented, err := doc.NewFromFiles(fset, files, pkg.ImportPath)
	if err != nil {
		return nil, fmt.Errorf("document %s: %w", pkg.ImportPath, err)
	}
	var declarations []string
	appendValues := func(values []*doc.Value) error {
		for _, value := range values {
			text, err := formatDeclaration(fset, value.Decl)
			if err != nil {
				return err
			}
			declarations = append(declarations, text)
		}
		return nil
	}
	appendFuncs := func(funcs []*doc.Func) error {
		for _, function := range funcs {
			decl := *function.Decl
			decl.Body = nil
			text, err := formatDeclaration(fset, &decl)
			if err != nil {
				return err
			}
			declarations = append(declarations, text)
		}
		return nil
	}
	if err := appendValues(documented.Consts); err != nil {
		return nil, err
	}
	if err := appendValues(documented.Vars); err != nil {
		return nil, err
	}
	if err := appendFuncs(documented.Funcs); err != nil {
		return nil, err
	}
	for _, typ := range documented.Types {
		text, err := formatDeclaration(fset, typ.Decl)
		if err != nil {
			return nil, err
		}
		declarations = append(declarations, text)
		if err := appendValues(typ.Consts); err != nil {
			return nil, err
		}
		if err := appendValues(typ.Vars); err != nil {
			return nil, err
		}
		if err := appendFuncs(typ.Funcs); err != nil {
			return nil, err
		}
		if err := appendFuncs(typ.Methods); err != nil {
			return nil, err
		}
	}
	slices.Sort(declarations)
	declarations = slices.Compact(declarations)
	return declarations, nil
}

func formatDeclaration(fset *token.FileSet, node any) (string, error) {
	var out bytes.Buffer
	if err := format.Node(&out, fset, node); err != nil {
		return "", err
	}
	return strings.TrimSpace(out.String()), nil
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "sdk-api-snapshot: "+format+"\n", args...)
	os.Exit(1)
}
